### ISSUE TITLE
[Feature Request] Per Dimension configs

### ISSUE THREAD

**Issue by ALJ323** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#1]
Requesting if at some point if you were going to maintsin this fork if it would be possible to have options in the config for whitelisting/blacklisting by dimension for meteors, passive radiation, structures/dungeons, and ore-generation(including features like the schist layer) for pack devs?

**Comment by SonicX8000** [comment]
I second this as custom structures can appear in other dimensions such as the Aether. For example... you can actually get one of those underground structures to appear in the Aether Dimension and... considering that that dimension is suppose to be floating islands & such... it's very strange to see something like this just generate in the void.

**Comment by Alcatergit** [comment]
Added in 1.8.4
