### ISSUE TITLE
Crash with exploded RBMK

### ISSUE THREAD

**Issue by DNIWE041** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#10]
If you explode your RBMK, leave from world \ game and try to re-join in world you get insta-crash.
My steps to reproduce:
1) Create world (im do it in creative).
2) Build and explode RBMK.
3) Leave world to main menu.
4) Re-join.
[crash-2022-11-28_12.44.54-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/10102404/crash-2022-11-28_12.44.54-server.txt)

**Comment by Alcatergit** [comment]
I can't replicate that. Try to break the rbmk debris blocks and update to the latest versions

**Comment by DNIWE041** [comment]
> I can't replicate that. Try to break the rbmk debris blocks and update to the latest versions

Yes, i made few test in newest versions and this bug self-fixed idk how.

**Comment by Alcatergit** [comment]
Found a way to replicate it. It should be fixed now, bc in dev it has not occured since my fix. So it will be in the next update
