### ISSUE TITLE
Bug: the infinite fluid barrel gets radiation when holding any radioactive items

### ISSUE THREAD

**Issue by idontkn0wman** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#102]
I tried with every radiation items and yet the infinite fluid barrel gets radiation from it Is this bug just me or does anyone also have this bug?

**Comment by Alcatergit** [comment]
Item Contamination is not a bug. If you get more then 5 Rad/s single items slowly get contaminated. You can decontaminate them with the decontaminator block, Nuclear Waste Disposal Drum or Liquidator Medal.
