### ISSUE TITLE
crash when going to/teleporting to a specific area sometimes

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#103]

**Comment by ghost** [comment]
[New Text Document.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11410410/New.Text.Document.txt)

**Comment by ghost** [comment]
also i should mention the server sometimes "survives" this event with a server tick taking like 40 seconds. Also the player who triggers this gets 0.1fps until the server crashes or "survives".

**Comment by Alcatergit** [comment]
Thats strange since the log only says something about a water splash particle

**Comment by ghost** [comment]
I removed two water geysirs near spawn and the issue went away. I am 99% sure thats where the water splash particle from the log is from. for speculation I am assuming particles got stuck in chunks the player is not in and when the player loads them they all get "released" this would explain the server lag along with player lag. also i have only noticed it happen in the spawn chunks and not other areas. maybe the partially always loaded world spawn chunks are needed for this crash to happen?

**Comment by Alcatergit** [comment]
That is a very likely explanation. Maybe the spawn chunks are special in some way.

**Comment by Alcatergit** [comment]
Geysirs will now stop spawning particles if there are too many
