### ISSUE TITLE
Small render issue with power armor chestplates

### ISSUE THREAD

**Issue by DNIWE041** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#11]
Small render issue with power armors - armor not following hand when you punch. With tool \ without tools - doesn't matter.
Affected armor:
1) Steel ranger armor (for example on screenshot).
2) AJR Power armor
3) HEV Mark IV
4) Remnants power armor
5) Lunar Cybernetics power armor (also winged chestplate)
6) Fau power armor

DNT Nano suit just don't have punch animation.

I think it's an old bug because i seen this in old Drillgon mod versions.

t45 power armor looks fine.

![image](https://user-images.githubusercontent.com/76884831/204248937-13e9bea0-ea61-415a-9ff3-8c97bbdf928e.png)

**Comment by Alcatergit** [comment]
Just fixed that bug for all those armors. It will be in the next update.
