### ISSUE TITLE
crashing existing saves

### ISSUE THREAD

**Issue by soggyfever4568** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#112]
so yeah I went to switch over from hbm reloaded to this mod and all my existing saves crash when trying to load with this error:
The game crashed whilst ticking block entity
Error: java.lang.RuntimeException: Slot 2 not in valid range - [0,2)

Is it possible for it to be fixed or is it a problem on my end?
if you need it here's the full crash log: https://pastebin.com/wmEJQLi5

**Comment by Alcatergit** [comment]
Ah thats an easy fix. Just remove the battery blocks before upgrading to extended.

**Comment by soggyfever4568** [comment]
ah thanks will do :D
