### ISSUE TITLE
Crash when launching version 1.9.5 on a server

### ISSUE THREAD

**Issue by slipwolff** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#115]
I have included the log below
[crash-2023-05-13_19.31.52-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11470324/crash-2023-05-13_19.31.52-server.txt)

To reproduce, launch the mod on a forge server. I have tried on two separate servers and both resulted in the same issue.

**Comment by TheRBMK** [comment]
same problem
i'm andrea

**Comment by Alcatergit** [comment]
Fixed it :)
