### ISSUE TITLE
RF to HE Converter does not convert power

### ISSUE THREAD

**Issue by slipwolff** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#118]
Connecting an RF to HE converter to an RF and HE network does not convert RF to HE.
The HE to RF converter operates normally.
Tested with Mekanism and RedstoneFlux API using the circuit below.
![2023-05-14_22 36 46](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/27822055/d36d9645-a7fb-4fa9-a881-ead845219779)
Included a copy of my log in case it may become useful.
[latest.log](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11472980/latest.log).

If this is not a bug and an error from my side, please close this issue.

**Comment by tyan-boot** [comment]
The new converter is missing the `IEnergyStorage` and `getCapability`, `hasCapability`.

**Comment by Alcatergit** [comment]
Fixed in 1.9.5-II
