### ISSUE TITLE
Fusion Reactor

### ISSUE THREAD

**Issue by BotBugad0** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#12]
Hello, I don't know if this is the right place to submit problems regarding HBM's mod Reloaded but if it is I found a problem regarding the fusion reactor, when accessing the plasma heater to check my deuterium and tritium levels and heat found out that the head was around 32500 instead of being around 3250 and because of that the reactor explodes I ran some tests on creative to find the problem.
![PlasmaHeater](https://user-images.githubusercontent.com/106037415/204324037-639d0669-c321-43b4-a8bf-aac9acec565b.png)
![FusionReactor](https://user-images.githubusercontent.com/106037415/204324369-22f066e6-95fc-45dc-aad9-3a0bf68b2877.png)
![BlownReactor](https://user-images.githubusercontent.com/106037415/204324878-caffee88-89c0-484d-810d-5b6f15a5d086.png)
![Blanket1](https://user-images.githubusercontent.com/106037415/204325253-99dc8815-c957-4c24-87b7-e7a1574fb9f5.png)
![Blanket2](https://user-images.githubusercontent.com/106037415/204325275-6a8e7c5e-d983-484c-bc98-9549fea8a029.png)

Those are the images of the Reactor's status.

**Comment by Alcatergit** [comment]
Fixed the issue yesterday. Will upload the new version soon.

**Comment by BotBugad0** [comment]
@Alcatergit Thank you and I am glad I could contribute.
