### ISSUE TITLE
Minecraft log filled with "PLATE APPROVED" message

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#121]
The minecraft log is constantly (Presumably every tick) has the line:

[02:36:27] [Client thread/INFO] [STDOUT]:
[com.hbm.items.gear.ArmorFSB:hasFSBArmor:121]: PLATE APPROVED

This competely fills the log to the point where this message makes up about 95% of the entire log. 
I suspect it's also the cause of having my game freeze after prolonged periods of playing, which only started after updating this mod.

**Comment by Alcatergit** [comment]
Old Bug. Use 1.9.5-I it is fixed there.
