### ISSUE TITLE
Solinium quad rod cannot be bred into burned quad rod

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#122]
Aka the "burned out quad schrabidium rod" for euphmium nuggets

**Comment by Alcatergit** [comment]
Ye that was very unbalanced way to get euphemium. Now we do it like 1.7.10 does it.

**Comment by CapitalismWouldveWorked** [comment]
cool, thanks for the fast response
