### ISSUE TITLE
Crash when using NTM Extended Edition, seemingly related with centrifuges.

### ISSUE THREAD

**Issue by Voxelstice** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#123]
My survival world is now bricked because of whatever change you (or whoever) did to the centrifuge.

[crash-2023-05-20_11.36.58-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11521906/crash-2023-05-20_11.36.58-server.txt)

i dont remember what version of NTM i last played this world in, but it's definitely NTM Reloaded.
Using version ``NTM-Extended-1.12.2-1.9.5-I``.

**Comment by Alcatergit** [comment]
Yes before updating to NTM Extended you need to break centrifuges and battery blocks.

**Comment by Voxelstice** [comment]
is it that hard to atleast patch the bug properly? i don't see what's so hard about adding another slot
the switching to different forks of ntm should be as seamless as possible
