### ISSUE TITLE
suggestion: zirnox reactor?

### ISSUE THREAD

**Issue by soggyfever4568** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#124]
hey I was wondering if there are any plans to re-add the zirnox reactor from the original?
https://ntm.fandom.com/wiki/ZIRNOX

**Comment by soggyfever4568** [comment]
update: just figured out it was deprecated and replaced with the research reactor.

**Comment by SmiteX134** [comment]
wdym, nuclear reactor was replaced with research reactor and zirnox stayed, it wasnt deprecated

**Comment by whatsapp2** [comment]
Opening a suggestion to add the Zirnox reactor just to later close it and say that Zirnox got replaced by the old ass research reactor ._.xd

**Comment by soggyfever4568** [comment]
https://ntm.fandom.com/wiki/ZIRNOX this is from the original mod but the last part of the first paragraph.
"(which has been deprecated since and replaced with the Research Reactor.)"

**Comment by Alcatergit** [comment]
I find the look and gui of the zirnox very ugly tbh. So i do not think i will add it.
A molten salt or pressurized water reactor would be way cooler.

**Comment by SmiteX134** [comment]
> https://ntm.fandom.com/wiki/ZIRNOX this is from the original mod but the last part of the first paragraph. "(which has been deprecated since and replaced with the Research Reactor.)"

u didnt understand, old nuclear reactor WAS replaced with research reactor and zirnox got added to take place of old nuclear reactor
