### ISSUE TITLE
Crash with Energy Control

### ISSUE THREAD

**Issue by aking4125** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#126]
Hello, upon adding this mod to our modpack. The game crashes with Energy Control.

NTM-Extended-1.12.2-1.9.5-II
EnergyControl-1.12.2-0.3.1

[crash-2023-05-24_23.19.46-client.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11560845/crash-2023-05-24_23.19.46-client.txt)
[debug.log](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11560847/debug.log)

**Comment by Alcatergit** [comment]
The energy system of NTM Extended was recently updated to that of the main NTM. That brought huge performance improvements as well as capability for diodes and a priority system.
So EnergyControl needs to update its NTM interface.
