### ISSUE TITLE
Suggestion: Audio to go along with digamma contamination

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#128]
Kinda like the coughing if you have lung cancer, I think something similar to the [Brain Sorcher sounds from Stalker](https://www.youtube.com/watch?v=un_xv--zq58) would fit well for high levels of digamma contamination, perhaps a similar grainy colored film over the player's screen but red instead of yellow would also be fitting for digamma, since it's supposed to be some kind of psychic contamination.

**Comment by Alcatergit** [comment]
Digamma contamination has sound effects since 1.9.6
