### ISSUE TITLE
No emissive textures

### ISSUE THREAD

**Issue by LeKripiY** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#13]
I am using optifine and I can't seem to find the emissives textures listend in the list of changes, i tried with the ores and none of them shine in the dark, I also tried with shaders on but still no emissive textures.

**Comment by TheForge129** [comment]
Emissive textures usually have to be added through a resource pack, OptiFine doesn't just know how to do it on it's own.

**Comment by LeKripiY** [comment]
Well it says this :
![image](https://user-images.githubusercontent.com/77859121/205722069-9c520fbf-4390-495d-96b6-76562ff65cc2.png)
So i thought it was built into the mod that if you have optifine installed the ores will glow for example.

**Comment by Alcatergit** [comment]
It seems like the emissive textures are only activated if you use a ressourcepack that also uses emissive textures.

**Comment by TheForge129** [comment]
IIRC emissive textures don't work with the default optifine rendering, you
need a shader of some sort

**Comment by LeKripiY** [comment]
Actually, I tried with shaders and I also didn't get the emissive textures, unless it only works with a very specific shader, i does not work.

**Comment by TheForge129** [comment]
Usually you need to enable both PBR and emissive textures

**Comment by LeKripiY** [comment]
nope, no emissives, can't convince me that they're in the mod, it's just not here
![image](https://user-images.githubusercontent.com/77859121/209451113-11e88032-6dfa-4381-823b-c0484037d463.png)
and i'm using the exact same shader as the creator said he was using on the mod page
![image](https://user-images.githubusercontent.com/77859121/209451124-861079fd-c97d-400a-a3da-837b2b6369a5.png)

**Comment by Alcatergit** [comment]
The ores are not what glows. Some items, models and blocks do. The Transmutation Device for example does.
