### ISSUE TITLE
Crash when placing certain turrets down.

### ISSUE THREAD

**Issue by ShadeAware** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#130]
Crash To Desktop error when placing down industrial-era turrets such as the Artillery Spitfire turret and small Tau turret.

**Testing Conditions**
Clean install of Minecraft 1.12.2 with no mods except HBM Extended. No Optifine. Default visual settings and HBM Configuration file.

**Crash Report**
https://pastebin.com/yQMZjkMi
Pastebin link for issue report brevity.

**Comment by Alcatergit** [comment]
Already fixed in dev. Next update includes it.
