### ISSUE TITLE
Minor nitpick but I feel like RBMK fuel lasts too long.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#133]
I wish that RBMK fuel didn't last as long as it does, especially since burning it up is needed for progression. It would be nice if RBMK fuel had half the lifespan before it fully depleted, or at least a config option to control the depletion rate. I've been experimenting in creative mode, trying to squeeze every last bit of flux I can from the reactors to try and burn up my fuel as quickly as possible, but that almost always results in the reactor melting down... I also kinda wish there was an "RBMK Coolant Channel", which was more effective at cooling a reactor, at the cost of using up coolant and not producing steam... Also an "RBMK Breeder Rod", which is exactly like the moderated fuel rod, but burns up fuel at twice or thrice the rate, or has a higher heat transfer rate so you can run fuel at much higher flux without melting down.

**Comment by Alcatergit** [comment]
Burn rate is tied to incoming flux. So one only needs to increase that. And to do that you can use sqrt function fuels with reflectors.
