### ISSUE TITLE
Bug: Thermal Series Crescent Hammers cause the items in crates to despawn when you right-click on them.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#138]
A crate full of random items:
![Screenshot 2023-06-04 005050](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/427776e3-2ca2-4b36-9f7c-c1e6b3124356)
Crescent Hammer, for those that have not used the Thermal mods, right-clicking on blocks rotates them:
![Screenshot 2023-06-04 005116](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/99dae634-f68c-46aa-a68a-2518674a0012)
The rotated crate has had its contents removed for some reason:
![Screenshot 2023-06-04 005134](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/612dbcdf-7fec-4216-ac4d-cc69840b74b4)

**Comment by Alcatergit** [comment]
Ye it can be used to bulk delete items. 
So if you dont want that then don't do it.
