### ISSUE TITLE
Wrong Silo hatch redstone signal placement

### ISSUE THREAD

**Issue by LeKripiY** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#14]
Currently you can only onpe a silo hatch when using them on this side
![image](https://user-images.githubusercontent.com/77859121/204906245-f50113c7-7cee-4b24-a583-7fe345e513c6.png)
but it would be more logical to power it from this side
![image](https://user-images.githubusercontent.com/77859121/204906396-0501d1a4-f531-4068-b69f-58eef951eec9.png)

**Comment by Alcatergit** [comment]
That is fixed in version 1.9.4
