### ISSUE TITLE
Bug: ReaSim RBMKs not producing steam, also steam channels and normal RBMK fuel rods uncraftable.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#141]
For some reason, there aren't any crafting recipes for the normal RBMK fuel rod blocks, nor the RBMK steam channels. I assumed at first that this was an attempt to phase them out in favor of ReaSim RBMKs, which I've never tried using before... I see that the reactor has a RealSim water level and a RealSim steam level, but there's one problem... The RBMK isn't producing any steam? 
![Screenshot 2023-06-05 025612](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/7c8ec056-32cc-4419-8be6-10d225c682a5)
![Screenshot 2023-06-05 025717](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/cd4a011b-6e04-436a-8c14-4c445742a500)

**Comment by Alcatergit** [comment]
Real Sim Boiling is turned off by default. Use "/gamerule dialReasimBoilers true" to turn it on. Super Dense Steam will then be generated.
Also RBMK Fuel Rods are craftable and to uncraft the core and skin temp need to be below 50°C.
