### ISSUE TITLE
Bug: For some reason the normal RBMK fuel rod and steam channel is uncraftible, or at the very least it doesn't show up in NEI.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#142]
I've been clicking on the RBMK fuel rod and the RBMK steam channel but nothing shows up in NEI, when I right-click the normal RBMK column it shows me the crafting recipe for the RealSim fuel rod but not for the normal fuel rod, nor the steam channel.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/f7bfd41f-54d7-472c-b8b4-3f8e0ebe67ef)

**Comment by Alcatergit** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/b83d6d94-e409-433b-b4d7-552411e951f7)
Works

**Comment by xenoulexi** [comment]
Hmm, likely that just something went wrong in my download then

**Comment by xenoulexi** [comment]
Nope, redownloaded the mod, still getting this problem, next I assumed it was a mod conflict somehow, but playing with this mod alone still can't craft the normal RBMK fuel rod blocks or steam channels, this is literally the only crafting recipe I have available.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/3f35c868-c16f-4679-b474-ff4b491fce8b)

**Comment by xenoulexi** [comment]
This is a real problem, I can't craft the fuel rods or the coolant channels at all, they don't show up in NEI, and trying to craft them anyway gives me nothing, so idk what to do. I've re-downloaded the mod but still nothing.

**Comment by xenoulexi** [comment]
Note: Apparently I fucked something up in the config files and somehow disabled them, fixed now

**Comment by Alcatergit** [comment]
> Note: Apparently I fucked something up in the config files and somehow disabled them, fixed now

Nice - ill consider it fixed.
