### ISSUE TITLE
Infinite Fluid Barrels don't work, and no Deuterium Tower.

### ISSUE THREAD

**Issue by Puridor** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#144]
There's no way to make Deuterium as the tower is missing at least in my version of the game.

The Infinite Fluid Barrels also don't work in any of the machines which make them pointless. This means I can't make a DFC.

This is a colossal shame and would be nice to have patched for creative testing.

**Comment by Alcatergit** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/73072f0a-3752-44ef-a5a7-f41548e3a384)
Please be more thorough next time. U make Deuterium via chemplant.

**Comment by Puridor** [comment]
> ![image](https://user-images.githubusercontent.com/117086491/244203789-73072f0a-3752-44ef-a5a7-f41548e3a384.png) Please be more thorough next time. U make Deuterium via chemplant.

Oh.. Huh. Thanks. Sorry about that.
