### ISSUE TITLE
Bug: Jetpack controls aren't working

### ISSUE THREAD

**Issue by EtheraelEspeon** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#147]
As above, none of these controls seem to work properly.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/42590699/fb4826b4-c1eb-45a4-a4d1-5db2b7ad4d2a)
I've tried binding them to all kinds of buttons, and none of them have made anything happen. I can kind of get around it by using the "Toggle Back" control, but i'm using the breakpack, and toggling my back accessory off still leaves it in hover mode, so if I walk off of a block I'll remain hovering in the air. 

As is, the breakpack is completely unusable if left attached to my chestplate, so i've been using it as a separate armor piece and swapping it for the chestplate when I need it. This is also made slightly more annoying by an unrelated issue of shift-click not moving the breakpack into my chest slot.

In case it helps, I'm also getting this little red icon in the bottom right of my screen with the jetpack equipped. I'm not sure what it means.
![2023-06-10_01 43 35](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/42590699/717c2a0d-99f0-4c1a-ab90-da4fb5812d48)

All of this behavior happens on version 1.9.6 with no additional mods installed.

**Comment by Alcatergit** [comment]
Fixed and will be in next update
