### ISSUE TITLE
Config for radiation factor of nuclear bombs (sellafite).

### ISSUE THREAD

**Issue by DNIWE041** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#15]
Hi! It's a small (or not?) enchantment for nuclear bombs.
With new system all nuclear bombs looks like dirty bombs, because they produce alot of high-radiation sellafite (for example simply 40mm grenade (Привет) easy can create 100-150 rad\s radiation level). 
So i have a question - can you make string in config for configure sellafite radiation? I think it can be in % of standart value.
Like that (i think minimum ~ 1% and maximum... 500%? idk):
```
# Controls the level of radiation of the sellafite. You can change it if you want to reduce \ increase radiation after nuclear explosion. 1.0 = 100%.
I:6.15_sellafiteRadiationFactor=1.0
```
Of course i can disable fallout stage of nuclear explosion, but it's looks not good when nuclear explosion has 0 radiation.

**Comment by Alcatergit** [comment]
Well nuclear bombs produce radiation. It is similar to how nuclear bombs in Fallout work. They create highly irradiated areas like the glowing sea.
