### ISSUE TITLE
QoL: Iron Bars connect to Universal Fluid Ducts

### ISSUE THREAD

**Issue by EtheraelEspeon** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#154]
As above.

Here's the context where I ran into this issue:
![2023-06-15_01 01 24](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/42590699/e666a9f2-cd60-4d84-9f15-0b98b14c31c2)
![2023-06-15_01 01 28](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/42590699/b23c5146-e879-4b2f-8dcd-a7ca76be662d)
(Those're ultra dense steam ducts)

Verifying with a minimal setup in creative, it seems to happen with all duct types, and connect to all fence-type blocks.
![2023-06-15_01 12 26](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/42590699/8db98a0e-e1d4-4f0b-b09e-18aaf38146c1)

Bottom to top the duct types are balefire plasma, kerosene, petroleum gas, and ultra dense steam
Left to right the blocks are Dark Steel Bars (Ender IO), Iron Bars, Steel Fences (Immersive Engineering), Oak Fences, and Nether Brick Fences

**Comment by Alcatergit** [comment]
Fixed it - will be in next update
