### ISSUE TITLE
Suggestion: Make Automatic Control Rods AZ-5 compatible

### ISSUE THREAD

**Issue by diyamomd45** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#157]
Sorry I had to due this under Issues but I really want this

**Comment by Alcatergit** [comment]
U could just use a normal and auto control rod in a row so if you want to az5 the normal control rod shuts it off. And in daily use the normal control rod would be 100% extended sothat the automatic one controls the reactor.

**Comment by diyamomd45** [comment]
Wow thanks

**Comment by Alcatergit** [comment]
You are welcome :)
