### ISSUE TITLE
RBMK Crane and Consol disappear after save and reload

### ISSUE THREAD

**Issue by Njet75** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#16]
RBMK Crane and Consol disappear after save and reload.
The consol still there but invisible.When i relink with linking tool it appear again

![console 1](https://user-images.githubusercontent.com/8996171/205163091-cf5bf58b-3030-4546-b864-77773e788af7.png)
![console2](https://user-images.githubusercontent.com/8996171/205163106-53326b1a-f368-471b-8863-0444606ea7f0.png)

/Michael

**Comment by DNIWE041** [comment]
Can confirm. Have same issue.

**Comment by Alcatergit** [comment]
I can see from the geiger texture and the console texture that you are not using the Alcater Edition. So this bug does not even belong to this mod.

**Comment by Alcatergit** [comment]
![2022-12-02_17 20 31](https://user-images.githubusercontent.com/117086491/205338549-6f9e1edd-5a08-4bd3-9b5f-fad2f829d80e.png)
This is how the console actually looks.

**Comment by DNIWE041** [comment]
![image](https://user-images.githubusercontent.com/76884831/205339098-4ffcf4a6-59d7-4543-8ab2-e82d40469277.png)
1.8.1 version of mod (not newest version), but i have this bug.
And after re-link
![image](https://user-images.githubusercontent.com/76884831/205339307-e9895ed0-ad55-42a2-9672-22e757102c73.png)
Maybe it's a bug from 1.7.10 or something like that, and coming to 1.12.2 after porting \ or optifine conflicts, idk.

**Comment by Njet75** [comment]
I make texturepacks and not done converting all textures to your version.
What version of optifine was used when creating your version?

**Comment by NONPLAYT** [comment]
same issue

**Comment by Njet75** [comment]
This issue seems to be fixed in latest versions.

**Comment by Alcatergit** [comment]
That is correct. It was fixed in 1.8.4a
