### ISSUE TITLE
Suggestion: Partial Nuclear Meltdowns.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#160]
Chornobyl was the only full nuclear meltdown in history, most nuclear meltdowns like Three Mile Island and Fukushima Daichi were only partial meltdowns.... For small nuclear reactors, I think this should happen if it runs out of coolant... Instead of exploding and melting into corium, the reactor turns into a damaged version of the reactor which releases radon gas, and if a small nuclear reactor runs out of water it should just stop producing heat since small nuclear reactors are supposed to be PWRs, which can't function without water as it is both moderator and coolant.
For the RBMKs, I think that they should only suffer a complete meltdown, the entire reactor exploding and spreading radiation everywhere, if the reactor columns go above 1500 degrees... If the reactor fuel heats up past its melting point that should cause a partial meltdown where only that specific column explodes, turning into corebblestone rather than solid or liquid corium.

**Comment by Alcatergit** [comment]
Partial RBMK Meltdowns are coming in the next update

**Comment by xenoulexi** [comment]
> Partial RBMK Meltdowns are coming in the next update

Nice... Also, sorry for spamming your issues with suggestions of mine, I absolutely love this mod, easily a mod I can't play MC without because I'm kinda obsessed with nuclear and particle physics. I'd gladly add all the suggestions I make myself, but I'm shit at coding, and what little I know is in Python and C++ since I use UE4 for my game projects, and so I don't even know where to begin making edits to Minecraft. Thus why I have to suggest all my ideas since I can't do them myself, lol.
