### ISSUE TITLE
Bug: Attachable masks in the wrong place

### ISSUE THREAD

**Issue by TMCAtom** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#166]
attachable masks appear to be about a block below where they should be, the helmets and masks themselves do not have this issue.
![image_2023-06-24_223458435](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/90524354/3d43c864-23cb-4971-ac56-4fa4098d1056)

**Comment by Alcatergit** [comment]
Fixed
