### ISSUE TITLE
QoL: RBMK model lag.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#168]
Can you please add a config option to render the RBMK columns without these little indentations, and to make the covers flush with the rest of the column, to help with lag. Because my PC can't handle particularly large reactors, or multiple reactors together within render distance of one another. Also, having a setting to make the fuel rods a single square instead of four octagons and having the control rods only be one rod that goes up/down instead of four, would probably help performance as well. Again, I'd prefer this to be a config option because I know plenty of other people might prefer the fancier-looking reactors but I want my PC to actually handle them.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/abb9f4a6-f5ca-486f-875f-65bcff0e6196)

**Comment by Alcatergit** [comment]
I found a way to increase the FPS of rbmks 4x
