### ISSUE TITLE
Suggestion: Toggle Fluid Item Registering in config

### ISSUE THREAD

**Issue by whatsapp2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#17]
An option to disable/enable the loading and generation of barrel/tank recipes for every fluid in the game. This would significantly decrease the ram usage when playing with large modpacks or some "heavy" mods like GregTech CEu. Just as a note, there's a disable all recipes option in the config, which is a bit of an overkill and not very useful for modpack devs. You would have to recode 200+ recipes manually using crafttwaeker or similar

**Comment by Alcatergit** [comment]
Just Coded that. It will be in the next update.
