### ISSUE TITLE
1.7.10's OpenComputers integration support

### ISSUE THREAD

**Issue by Zduniusz** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#171]
Hi, I recently found NTM (1.7.10 version) and was super excited about it and how well it integrates with OC (Looking at wiki's [page](https://ntm.fandom.com/wiki/OpenComputers_Integration)

Unfortunately, it seems that a significant portion of this support was lost in forks for 1.12.2.
According to the wiki's [page](https://ntm-alcateredition.fandom.com/wiki/OpenComputers_API), only the reactor is available.

Are there any plans to add the rest of the components?

**Comment by Alcatergit** [comment]
RBMK Reactor and RBMK Crane have OC compatibility. If u want other machines feel free to make a pull request.
