### ISSUE TITLE
Fluid Burner and Steel Furnace need higher TU Capacity

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#173]
When the fluid burner uses endgame fluids such as nitan fuel, the TU capacity maxes out at 2mb/t, bottlenecking the TU output for steel furnaces. Changing the TU capacity to around 2,500,000 should fix this. 

This same problem would affect the steel furnace which would need it's capacity increased too, roughly to 1,000,000 max TU.

**Comment by Alcatergit** [comment]
Fluid burner throughput can be increased by rightlicking it with a screwdriver.
And for Steel Furnaces people can use multiple ones.

**Comment by CapitalismWouldveWorked** [comment]
I didn't realize that was intentional. Thanks for the fast reply.

**Comment by Alcatergit** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/74eb4e6c-304c-46c1-a151-ce9129d8edb5)
Sure yw
U can use the screwdriver to increase the burnrate of the fluid burner and a desh drill to decrease it.
