### ISSUE TITLE
Bug: RF to HE converter using FE (forge energy) even when HE powered machines are full

### ISSUE THREAD

**Issue by HighQGithub** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#174]
Whenever HE machines are connected to an RF to HE converter, RF will continuously drained despite nothing running. I'm assuming it relates to the changes you made regarding the RF to HE converters in the previous update. You may have removed the ability for them to store energy, however, the converters still think they are supposed to continuously draw energy despite the storage method never being called on. To fix this issue, try setting a maximum amount of energy the converter blocks can store (i.e, 10,000 HE) before they stop drawing power. If the storage decreases below 10,000 due to machines drawing energy, it will enable power to be inputted again. I'd recommend making it call on these updates at a slow-ish tickrate though to prevent serverside lag.

**Comment by Alcatergit** [comment]
Fixed - will be in next update
