### ISSUE TITLE
The crt-support for assembly does not work as expected.

### ISSUE THREAD

**Issue by eterraria** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#178]
i can use crt to delete recipes of assembly, but failed to add recipes. There was no new template generated.

i tried to fix this, and it works:

replace line 61 of com/hbm/handler/crt/Assembler.java with
ComparableStack recipeKey= new ComparableStack(this.output);
AssemblerRecipes.makeRecipe(recipeKey, compInputs, this.duration);
AssemblerRecipes.recipeList.add(recipeKey);

it seems that the problem is that new recipe would not be added to "recipeList", which is responsible for generating templates.

**Comment by Alcatergit** [comment]
Fixed, next version will also have a "replaceRecipe" function
