### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by Heketiitus** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#179]
- In the excavator there's a typo, "Veign mining"
- The mineral of the bedrock ore cannot be translated. For example of iron bedrock ore you can only translate the bedrock ore part. If I wanted to translate it into Finnish, it would become "ironperuskalliomalmi" where it should be "rautaperuskalliomalmi".
- item.fluid_barrel_empty.name is not affected by translation at all. Same for item.fluid_tank_empty.name
- For the fluid buckets it doesn't seem possible to translate the "bucket" part.

**Comment by Alcatergit** [comment]
Fixed the Vein mining
