### ISSUE TITLE
containment door and sliding door problem

### ISSUE THREAD

**Issue by NONPLAYT** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#18]
So I think, I found texture bug on door with window. Does it need to be fixed in source code?

![image](https://user-images.githubusercontent.com/76615486/205508556-9d72b686-a955-412e-9fc3-24eeeb95cbf3.png)

**Comment by Alcatergit** [comment]
What is the bug here?

**Comment by NONPLAYT** [comment]
> What is the bug here?

on the big sliding door with window

**Comment by Alcatergit** [comment]
This is a window and you can look through it. So what is the problem here? Be more specific

**Comment by NONPLAYT** [comment]
outside the window there is a containment door. sometimes I see it and I don't see it. I don't know what it is but I think it's a bug
https://www.xbox.com/play/media/VTGJN24222

**Comment by NONPLAYT** [comment]
and I don't know if it's on my side and if it's my problem or not

**Comment by Alcatergit** [comment]
It is caused by culling of the models behind the door. I dont think there is a way around this.
