### ISSUE TITLE
Freezing and crashes with wyrms of nyrus when making a new world or entering new dimension 

### ISSUE THREAD

**Issue by Gerald4567** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#186]
[crash-2023-07-05_17.04.13-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11982161/crash-2023-07-05_17.04.13-server.txt)
My game freezes when I add dimension ids to the invasion wyrms of nyrus configs while I submitted the issue the GitHub for wyms of nyrus I was told  by the mod author that it was related to this mod so I'm posting it here to hopefully get more help on this issue

**Comment by Alcatergit** [comment]
If it keeps happening you can disable combustible gas pockets in that dimension.
