### ISSUE TITLE
Too many particles crashing servers.

### ISSUE THREAD

**Issue by NoMoreUsernames999** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#19]
Not sure if this would really be considered a bug or an enhancement, but I'd like to suggest lowering the overall number of particles generated by effects, specifically the dense clouds of tiny particles some effects generate (these honestly should be reduced by maybe half). I have a decently powerful computer (capable of running pretty much anything) and a good server, and the particles are absolutely killing them. 
In singeplayer, I experience lag if more than four rocket turret explosions are in view. Same with if there is more than one howitzer turret explosion (the old wip one), more than 3 anti ballistic explosions, etc. The vapor geysers are especially bad, with only one needed in the field of view to tank the fps to 15-20. On the server side of things it's even worse, as the server crashes because the watchdog terminates it after a tick takes longer than 60 seconds. If there are more than 10 missiles flying around in loaded chunks with players looking at them, it's pretty much a guaranteed crash.

**Comment by Alcatergit** [comment]
Some particle effects have been reduced.
