### ISSUE TITLE
Blast furnace

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#191]
The blast furnace keeps clearing items in it, even the fuel loaded. Is it my issue, or is there problem in the code ?

**Comment by Alcatergit** [comment]
What exactly do you mean with clearing of items? Which slots are effected, when does it happen, etc.

**Comment by ntmleafia** [comment]
k i take it back it seems like a compatibility issue between a mod called tiquality
