### ISSUE TITLE
Is there a way to remove the new mechanics of opening large doors through redstone?

### ISSUE THREAD

**Issue by Wekdol** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#192]
I can't get used to the new mechanics, and I don't want to switch to the old version because there is noticeably less content. Please help me.

**Comment by xenoulexi** [comment]
You can just use buttons...

**Comment by Alcatergit** [comment]
Exactly

**Comment by Wekdol** [comment]
> You can just use buttons...

It closes right after opening

**Comment by Alcatergit** [comment]
If you want it open you can use a lever. It will be open when redstone is on and closed when redstone is off.
