### ISSUE TITLE
red copper wire does not connect to advanced factory electricity port

### ISSUE THREAD

**Issue by Heketiitus** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#194]
i dont know if this is the case for the basic factory but even though my advanced factory is properly built it has an energy cluster inside and this i built it in a way that has worked in earlier versions of the mod, red copper wires just do not connect to the electricity port.

**Comment by SmiteX134** [comment]
same with basic factory

**Comment by Alcatergit** [comment]
Fixed, will be in the next version
