### ISSUE TITLE
No way to remove coal dust disease in config

### ISSUE THREAD

**Issue by Aroraptor** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#195]
There is no part in the config where you can remove the effects.

**Comment by CapitalismWouldveWorked** [comment]
1.9.5-I added the option to remove black lung. But if you mean the removal of the particles produced from mining coal ore then yes, the dust particles still appear even if the config has coal gas turned off.

**Comment by rsiebertdev** [comment]
At the moment, there doesn't appear to be any toggle that allows you to disable the black lung disease.
https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/blob/3450a750a2e2992eb444a89bf4837069eccf3575/src/main/java/com/hbm/capability/HbmLivingProps.java#L165-L181

I think this fork is currently missing a lot of config options compared to TheOriginalGolem's version being [85 commits behind](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/compare/Custom-1.12.2...TheOriginalGolem:Hbm-s-Nuclear-Tech-GIT:Custom-1.12.2). It could be worth going through all the missing changes and seeing what we could merge, one of them being the black lung toggle.

**Comment by rsiebertdev** [comment]
Unless it's the `Added Coal Config toggle` as per the patch notes...? Not entirely sure what that one does, and I'm kinda too lazy rn to search the SRC lmao

**Comment by CapitalismWouldveWorked** [comment]
I recall switching from Golem's version to Alcater's, when I did the option was gone until the 1.9.5-I update, this is what my config say now (at line 53):

    # Enables call lists for a few models, making them render extremely fast
    B:1.26_callListModels=true
    B:1.26_enableAsbestosDust=false
    B:1.26_enableCoalDust=false
    B:1.27_enableBabyMode=true

I am currently using this feature in survival world with the most recent release and I get no lung problems when mining coal, in spite of the particles still appearing.

**Comment by Shibva** [comment]
This just disables the mechanic
