### ISSUE TITLE
PaA Leg Reinforcements & PaA "good ol' shoes"

### ISSUE THREAD

**Issue by BestDad21** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#199]
PaA Leg Reinforcements & PaA "good ol' shoes" have the same crafts

![1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/139028394/ea254185-e29d-48eb-8029-f8743a676a62)
![2](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/139028394/e5460a2b-30f5-4679-824e-b229df42a064)

Another problem is that I can't delete crafts using CraftTweaker how can i do it then?

**Comment by Alcatergit** [comment]
PaA gear crafting is now fixed
