### ISSUE TITLE
QoL: Sellafite block generation visual glitch before first save of world

### ISSUE THREAD

**Issue by LeKripiY** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#202]
Hello, for some reason, the generation of stellafite started to do this in my worlds, I have optifine installed but it never did that before, I was wondering if you got any ideas ?
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/77859121/21a9d764-21e4-4b93-b84c-d23c79e05d6d)

I got a chunk in with the same glitch near and using Random Things Chunk scanner, I saw that they both had stellafite.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/77859121/82280a47-8d31-4205-89f1-10b47441b93d)

**Comment by LeKripiY** [comment]
Also I would like to add that any entity that goes into here will be transparent, mobs like creeper can walk on the block that are "there" (i saw that using a health bar mod over the mob head), but for players you fall down as if you had slow falling.

**Comment by LeKripiY** [comment]
Update on the issue, I still have the same problem even without optifine.

**Comment by Alcatergit** [comment]
The Sellafite Blocks will be removed in the next update
