### ISSUE TITLE
Bug: Flipped Breakpack behavoir

### ISSUE THREAD

**Issue by Aroraptor** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#203]
The breakpack is turned on and off with the 'toggle back' button. That works. The issue is that the pack works when it is toggled off. I can fly and won't lose any fuel. When it is on it does not work, makes noise, and uses fuel.

**Comment by Alcatergit** [comment]
Does that happen in newly created worlds or just old ones?

**Comment by Alcatergit** [comment]
Fixed - will be in next update
