### ISSUE TITLE
hbm/jei machine fluids visual improvements

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#206]
Would it be possible to:
1. Make it so fluids in jei can show the recipes used in machines, rather than doing so by clicking the fluid tank then the hbm fluid icon.
2. Make it so the fluids in the crafting recipes use the actual fluid texture rather than the hbm fluid icon (or color the fluid icon like in TheOriginalGolem's version)

Thanks!

**Comment by Alcatergit** [comment]
Nope

**Comment by CapitalismWouldveWorked** [comment]
L
