### ISSUE TITLE
the pipes and the cables is lagging so much

### ISSUE THREAD

**Issue by VALERIMAK253** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#214]
the new 'round' cables and fluid pipes is lagging the game so much, i'm getting like 40 fps with only 2 reactors and my friend getting 10 fps, please make an option to use the old models

**Comment by Alcatergit** [comment]
The old ones are also not faster. When you want speed the best is to use the full block versions of ducts and cables as they render very quickly.
