### ISSUE TITLE
If nukes are going to evaporate water it should be in a circle not square

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#217]
This looks kinda weird
![Screenshot_1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/87919245/08892309-9023-4bb5-b8d3-4662500219ae)

**Comment by ghost** [comment]
This should also have the benefit of faster calculations since less blocks need to be changed

**Comment by Alcatergit** [comment]
That was tested when adding the water draining. The thing is that water is not a static block which stays where it is. so if you make a large circle in the water then the edges would fill up and look very irregular and weird.

**Comment by Alcatergit** [comment]
Before - a superflat ocean
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/b2048d91-ab35-487e-bdf5-e1777fdedd65)

**Comment by Alcatergit** [comment]
Directly after doing _//cyl 0 100 -100_ using worldedit (creating a 100m air cylinder)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/094cf105-c3f8-453f-9431-1767fe92a0c1)

**Comment by Alcatergit** [comment]
The diagonals start to fill up from below
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/2eda88b0-cff0-465b-9b47-c83471302d75)

**Comment by Alcatergit** [comment]
They go up and to the center until it is completely filled again.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/6806908e-490b-4b5c-8742-d16217466328)

**Comment by Alcatergit** [comment]
Filled like before - What we learn is that when creating dry arreas we must avoid creating diagonals in the water edge.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/ebe418d0-4708-47bf-a7b5-0eccf9c08d50)
