### ISSUE TITLE
Qol: Large Vanilla Explosions look strange

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#218]
3x3x3 cube of explosive charge
![Screenshot_2](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/87919245/d13b0ae7-fdc4-4031-aa0a-e3eaf5c7837a)
3x3x3 cube of semtex
![Screenshot_1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/87919245/d16be790-4957-4272-b4c0-5e4655fc31d4)

**Comment by Alcatergit** [comment]
That is the vanilla explosion algorithm which can also be seen at very big fire charge explosions
