### ISSUE TITLE
My Modded World Crashed when Loading Extended Edition of HBMs Nuclear Tech Mod 

### ISSUE THREAD

**Issue by Nuclearenergy1415** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#225]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 8/31/23 3:15 AM
Description: Ticking block entity

java.lang.RuntimeException: Slot 6 not in valid range - [0,6)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
	at com.hbm.tileentity.machine.TileEntityMachineCentrifuge.getSpeedLvl(TileEntityMachineCentrifuge.java:195)
	at com.hbm.tileentity.machine.TileEntityMachineCentrifuge.func_73660_a(TileEntityMachineCentrifuge.java:247)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
	at com.hbm.tileentity.machine.TileEntityMachineCentrifuge.getSpeedLvl(TileEntityMachineCentrifuge.java:195)
	at com.hbm.tileentity.machine.TileEntityMachineCentrifuge.func_73660_a(TileEntityMachineCentrifuge.java:247)

-- Block entity being ticked --
Details:
	Name: hbm:tileentity_machine_centrifuge // com.hbm.tileentity.machine.TileEntityMachineCentrifuge
	Block type: ID #985 (tile.machine_centrifuge // com.hbm.blocks.machine.MachineCentrifuge // hbm:machine_centrifuge)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-53,67,194), Chunk: (at 11,4,2 in -4,12; contains blocks -64,0,192 to -49,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #985 (tile.machine_centrifuge // com.hbm.blocks.machine.MachineCentrifuge // hbm:machine_centrifuge)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Nether Secure Nuclear (Backup)
	All players: 1 total; [EntityPlayerMP['DarkFusionPro98'/419, l='Nether Secure Nuclear (Backup)', x=150.84, y=59.03, z=460.06]]
	Chunk stats: ServerChunkCache: 881 Drop: 0
	Level seed: 368462672941697317
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6391722312 bytes (6095 MB) / 9859760128 bytes (9403 MB) up to 28633464832 bytes (27307 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx30G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                   | Source                                            | Signature                                |
	|:------ |:----------------------- |:------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                    | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                     | 9.42                      | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                 | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2860              | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | techguns_core           | 1.12.2-1.0                | minecraft.jar                                     | None                                     |
	| LCHIJA | securitycraft           | v1.9.7                    | [1.12.2]+SecurityCraft+v1.9.7.jar                 | None                                     |
	| LCHIJA | bspkrscore              | 7.6.0.1                   | [1.12]bspkrsCore-universal-7.6.0.1.jar            | None                                     |
	| LCHIJA | treecapitator           | 1.43.0                    | [1.12]TreeCapitator-client-1.43.0.jar             | None                                     |
	| LCHIJA | csb_armorstand          | 1.0.4                     | ArmorStandGUI-1.12-1.0.4.jar                      | None                                     |
	| LCHIJA | atomicscience           | 1.12.2-3.0.6.19           | Atomic-Science-1.12.2-3.0.6b19.jar                | None                                     |
	| LCHIJA | jei                     | 4.24.2                    | HadEnoughItems_1.12.2-4.24.2.jar                  | None                                     |
	| LCHIJA | betterstorage           | 3.0.0.3                   | BetterStorageToo-1.12.2-3.0.0.3.jar               | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.1                     | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
	| LCHIJA | cofhcore                | 4.6.6                     | CoFHCore-1.12.2-4.6.6.1-universal.jar             | None                                     |
	| LCHIJA | cofhworld               | 1.4.0                     | CoFHWorld-1.12.2-1.4.0.1-universal.jar            | None                                     |
	| LCHIJA | dumpsterdiving          | 1.0 - 1.12.2              | Dumpster+Diving+1.5.2+-+1.12.2.jar                | None                                     |
	| LCHIJA | ic2                     | 2.8.222-ex112             | industrialcraft-2-2.8.222-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | energycontrol           | 1.12.2-0.2.8              | EnergyControl-1.12.2-0.2.8.jar                    | None                                     |
	| LCHIJA | engineersdecor          | 1.1.5                     | engineersdecor-1.12.2-1.1.5.jar                   | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | engineerstools          | 1.0.5                     | engineerstools-1.12.2-1.0.5.jar                   | None                                     |
	| LCHIJA | extrautils2             | 1.0                       | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCHIJA | zerocore                | 1.12.2-0.1.2.9            | zerocore-1.12.2-0.1.2.9.jar                       | None                                     |
	| LCHIJA | bigreactors             | 1.12.2-0.4.5.68           | ExtremeReactors-1.12.2-0.4.5.68.jar               | None                                     |
	| LCHIJA | forgelin                | 1.8.3                     | Forgelin-1.8.3.jar                                | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar      | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar      | None                                     |
	| LCHIJA | lizardfurnituremod      | 1.1.0                     | FurbishCraft+1.2.1+[1.12.2].jar                   | None                                     |
	| LCHIJA | trashcansreborn         | 1.1.0                     | GarbageBins-1.1.1.jar                             | None                                     |
	| LCHIJA | waila                   | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | theoneprobe             | 1.4.28                    | theoneprobe-1.12-1.4.28.jar                       | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.7                     | ThermalFoundation-1.12.2-2.6.7.1-universal.jar    | None                                     |
	| LCHIJA | immersiveengineering    | 0.12-98                   | ImmersiveEngineering-0.12-98.jar                  | None                                     |
	| LCHIJA | immersivechemical       | 1.1.6                     | immersive-chemical-engineering-1.1.6-shadowed.jar | None                                     |
	| LCHIJA | industrialdecor         | V-22.1120                 | industrialdecor_1.12.2_v21.1120.jar               | None                                     |
	| LCHIJA | industrial_decor        | 1.0.0                     | industrialdecor_1.12.2_v21.1120.jar               | None                                     |
	| LCHIJA | teslacorelib            | 1.0.18                    | tesla-core-lib-1.12.2-1.0.18.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2             | industrialforegoing-1.12.2-1.12.13-237.jar        | None                                     |
	| LCHIJA | industrialmeat          | 1.12-1.0.2                | industrialmeat-1.12-1.0.2.jar                     | None                                     |
	| LCHIJA | industrialrenewal       | 0.21.8                    | IndustrialRenewal_1.12.2-0.21.8.jar               | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCHIJA | machinemod              | ${version}                | MachineMod-1.12.2-1.1-Pre-ALPHA-Build-300.jar     | None                                     |
	| LCHIJA | magneticraft            | 2.8.5                     | Magneticraft_1.12-2.8.5-dev.jar                   | None                                     |
	| LCHIJA | mcjtylib_ng             | 3.5.4                     | mcjtylib-1.12-3.5.4.jar                           | None                                     |
	| LCHIJA | modelloader             | 1.1.7                     | modelloader-1.1.7.jar                             | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43                  | MrTJPCore-1.12.2-2.1.4.43-universal.jar           | None                                     |
	| LCHIJA | nomobbat                | 1.1                       | NoBat-1.12.2-frg14.23.3.2655.jar                  | None                                     |
	| LCHIJA | nonevaporation          | 1.0.1                     | NonEvaporation_1.9-1.0.1.jar                      | None                                     |
	| LCHIJA | nonvflash               | 1.2.0                     | NoNVFlash-1.12.2-1.2.0.3-universal.jar            | None                                     |
	| LCHIJA | hbm                     | NTM-Extended-1.12.2-1.9.8 | NTM-Extended-1.12.2-1.9.8.jar                     | None                                     |
	| LCHIJA | nuclearcraft            | 2.18zzz                   | NuclearCraft-2.18zzz-1.12.2.jar                   | None                                     |
	| LCHIJA | patchouli               | 1.0-23.6                  | Patchouli-1.0-23.6.jar                            | None                                     |
	| LCHIJA | performant              | 1.12.2-1.5                | performant-1.11.jar                               | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-Base.jar              | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar       | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar       | None                                     |
	| LCHIJA | projectred-fabrication  | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-fabrication.jar       | None                                     |
	| LCHIJA | projectred-illumination | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-lighting.jar          | None                                     |
	| LCHIJA | projectred-exploration  | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-world.jar             | None                                     |
	| LCHIJA | questionablyimmersive   | @VERSION@                 | questionablyimmersive-1.12.2-0.1.0.jar            | None                                     |
	| LCHIJA | rftools                 | 7.73                      | rftools-1.12-7.73.jar                             | None                                     |
	| LCHIJA | rftoolspower            | 1.2.0                     | rftoolspower-1.12-1.2.0.jar                       | None                                     |
	| LCHIJA | rsgauges                | 1.2.8                     | rsgauges-1.12.2-1.2.8.jar                         | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | lteleporters            | 1.12.2-3.0.2              | simpleteleporters-1.12.2-3.0.2.jar                | None                                     |
	| LCHIJA | steamworld              | 0.4.0.2                   | SteamWorld+1.12.2-0.4.0.2.jar                     | None                                     |
	| LCHIJA | techguns                | 2.0.2.0                   | techguns-1.12.2-2.0.2.0_pre3.2.jar                | None                                     |
	| LCHIJA | texfix                  | 4.0                       | TexFix+V-1.12-4.0.jar                             | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.7                     | ThermalExpansion-1.12.2-5.5.7.1-universal.jar     | None                                     |
	| LCHIJA | thermalcultivation      | 0.3.6                     | ThermalCultivation-1.12.2-0.3.6.1-universal.jar   | None                                     |
	| LCHIJA | thermaldynamics         | 2.5.6                     | ThermalDynamics-1.12.2-2.5.6.1-universal.jar      | None                                     |
	| LCHIJA | thermalinnovation       | 0.3.6                     | ThermalInnovation-1.12.2-0.3.6.1-universal.jar    | None                                     |
	| LCHIJA | wastelands              | 1.2.2                     | wastelands-1.2.2-null-universal.jar               | None                                     |
	| LCHIJA | wrcbe                   | 2.3.2                     | WR-CBE-1.12.2-2.3.2.33-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | zettaindustries         | 1.3                       | zettaindustries-1.3-1.12.2-161.jar                | None                                     |
	| LCHIJA | immersiveintelligence   | 0.2.1                     | immersiveintelligence-0.2.1.jar                   | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| LCHIJA | industrialwires         | 1.7-36                    | IndustrialWires-1.7-36.jar                        | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCHIJA | nofog                   | 1.12.2-1.12.2-1.0.3.0     | NoFog-1.12.2b3.jar                                | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
	| LCHIJA | teslacorelib_registries | 1.0.18                    | tesla-core-lib-1.12.2-1.0.18.jar                  | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7.jar)
  
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DarkFusionPro98'/419, l='Nether Secure Nuclear (Backup)', x=150.84, y=59.03, z=460.06]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 19
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 474.44
	OpenGlRenderer: NVIDIA GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by DNIWE041** [comment]
Remove all centrifuges and energy storage blocks BEFORE update from an older version mod to a newer one.
Or you can try to turn on removing erroring tile entitys in forge config (use at your own risk).
