### ISSUE TITLE
[Rendering Bug] Astral Sorcery skybox z-fighting wtih sky renders

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#226]
The bobmazon sattilight render and Digamma sky renders in the skybox appears to conflict with Astral Sorcerys Skybox

To reportduce just have Astral and HBM Extended in the instance and set the time to night

**Comment by Alcatergit** [comment]
Skybox config toggle will be in the next version

**Comment by Shibva** [comment]
I'm hoping it's able to adjust instead of Z fighting; would be nice to see both of them without them conflicting in the night sky

**Comment by Shibva** [comment]
@Alcatergit thanks for adding this but is there a way to have the renders rendered slightly above the skybox?
