### ISSUE TITLE
[Render Bug] Special fullbody armor renders should overide skin layers

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#227]
I think I made a report on this for 1.7.10 with FoamFix since that version backports skin layers

![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/0d93855c-91c4-4e19-99af-0e6c49849a82)
These renders are being clipped though due to the player's outer skin layer.
a fix for this would be to override its ability to render when a specific armor piece is put on (while maintaining client hand renders via first-person view).
This would be reserved for special armor rendering like with the power armors.

this would put a halt on the rendering clash. Disabled rendering would go as follows

Helmet = Hat
Chestplate = Jacket, Right and Left Arms
Leggings = Left and Right Pants Leg

**Comment by Shibva** [comment]
Note: white spot on head is part of my skin and the sleves can be partially seen at the end tips

**Comment by Shibva** [comment]
@Alcatergit I think the easiest thing to do is to add some sort of check that apples, certain clothing elements, depending on what slot (head for helmet, sleeves and shirt for chestplate, pants for leggings, and shoes for boots)

This should be somewhat easy to implement since the game already has an option for that to toggle between such states so it could be easy to have a check to see if the player has that setting enabled and if it is and they're wearing a designated set of armor, it would override the render setting. Probably very easy to implement, but what do I know?

**Comment by Shibva** [comment]
I just came to realize that the t45 has this already in place; should be easy to implement it to the other armors

**Comment by Alcatergit** [comment]
Fixed it - will be in next update
