### ISSUE TITLE
suggestion dfc half mirror half glass

### ISSUE THREAD

**Issue by username90001** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#23]
dfc block that will reflect half of laser energy to one side and will let other half pass through it

**Comment by Alcatergit** [comment]
What would be the benefit of this semitransparent mirror block?

**Comment by username90001** [comment]
laser will reflect half of it back to core and create infinite loop that will create infinite amout of energy and create strongest reactor in history of minecraft

**Comment by Alcatergit** [comment]
You can do that using cables already. That is an old trick

**Comment by username90001** [comment]
what

**Comment by Alcatergit** [comment]
https://www.youtube.com/watch?v=0qRJOUAuMWY

**Comment by username90001** [comment]
> https://www.youtube.com/watch?v=0qRJOUAuMWY

oh i meant not this i mean like a controlable half mirror glass that will reflect some light and absorb to turn into power
- it will always increase power because half will reflect get much stronger and half again - i mean infinitly increasing power not just this
