### ISSUE TITLE
Large Boilers

### ISSUE THREAD

**Issue by ElPudgino** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#237]
Large electric boiler is about 3 times slower than small one but uses 3 times more energy. Large RTG boiler with 300 pellet heat is about 5 times slower than small RTG boiler with 40 pellet heat.

**Comment by CapitalismWouldveWorked** [comment]
Doesn't the RTG firebox and electric firebox already fulfill these roles? The electric firebox is already more inefficient than a solid/fluid firebox, whereas the rtg firebox seems mostly for automation sake due to the relatively low TU output.

**Comment by Alcatergit** [comment]
The electric boiler is for getting small amounts of hot fluid. When you want to go industrial then do that and get the big Boiler.
