### ISSUE TITLE
Chunk Radiation rapidly decreasing in an enclosed space

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#246]
well it's me again and i'd like to talk about enclosed space radiation issues AGAIN

just as i put on name of this issue, yes, chunk radiation rapidly decreases in enclosed space, much faster than how it decreases when outside

Inside
https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/7f0fd821-3dc5-4ad3-b2b4-27a0dfc2a21c

Outside
https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/11e8cc4b-31e3-4d77-9cbe-ed4684dd06a5

At this point the radiation absorbers are nothing more than an useless, crafting ingredient. What's their purpose now?

**Comment by Alcatergit** [comment]
Radiation absorbers are used when you have a chunk radiation source which you can not remove.

**Comment by ntmleafia** [comment]
I mean I just found it weird when lethal levels of radiation just instantly disappears once a source block is removed in enclosed space.
If that’s how it works, okay then.
