### ISSUE TITLE
Bug: Industrial Generator can't transfer energy and receive fluids

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#247]
The Industrial generator doesn't seem to transfer it's energy to any machine or energy storage block. 

The screenshot shows it being tested with energy cables, red copper blocks, directly with a energy storage block, and connected to an assembly machine. None receive power.
![20230917112608_1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121686729/0f456d28-f88f-4c62-8cc8-2999ee456064)

The industrial generator also can't receive fluids through fluid ducts.

**Comment by KauaiMoho** [comment]
I concur. Put an issue on discord.

**Comment by CapitalismWouldveWorked** [comment]
I tested this further in a creative world, even covering it with cables does nothing.

This has only become an issue after the energy update, hence why this still works in the older versions.

**Comment by Alcatergit** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/117086491/62f5ab11-24f3-4ebd-bfc4-ce002b20caff)
They connect from below the edges
