### ISSUE TITLE
Versitile chipset recipe error

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#248]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/b611ed7d-b38f-4f3b-a834-3928b11edab3)
I think this was supposed to be a capacitor board

**Comment by Shibva** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/438e158c-9979-4817-96d0-d9c5f5681c33)
this one too

there might be a few more out there

**Comment by Alcatergit** [comment]
Fixed - Will be in the next update
