### ISSUE TITLE
Spinny light doesn't spin

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#249]
Spinny light doesn't spin

**Comment by GenericBrandName** [comment]
This happens to me as well. Every time I make a new world it works for a while, but seemingly at random all spinny lights permanently break in that world.

![Example Gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTJxYnJwcXB2ZnA1dm9oMzl2cnVlMHM2dmRhejRkNmFibHp2dzc2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/s09QpTkalPcNi5nZYk/giphy.gif)
[Example Gif](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/69471170/a16d9d86-f12e-48dd-8d07-53c38d7294a4)

**Comment by GenericBrandName** [comment]
OH MY GOD I FIGURED IT OUT!!!

After looking at the code, I realized it uses the world time to spin properly, so setting doDaylightCycle back to true fixed it!

**Comment by Alcatergit** [comment]
Fixed it - will be in next update
