### ISSUE TITLE
BUG:The RBMK explosion causes the game to crash

### ISSUE THREAD

**Issue by Pastrine** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#251]
When you put some RBMK fuel like RBMK DIGAMA fuel rods in the RBMK and place the reflector in the RBMK, it causes a java.lang.IllegalArgumentException:bound must be positive

add 1 to the nextInt method in TileEntityRBMKBase.java:129

if(this.jumpheight > 0 || world.rand.nextInt((int)(25D*maxHeat()/(this.heat-jumpTemp+200D)+1)) == 0){

**Comment by Alcatergit** [comment]
Fixed
