### ISSUE TITLE
[Mod compat] Mekanism

### ISSUE THREAD

**Issue by MiniRaptor** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#252]
You can't use HBM ores in Mekanism machines, and you also can't use energy from Mekanism to power HBM machines. If you can do something about this, I would be very grateful for the introduction of such compatibility.

**Comment by SmiteX134** [comment]
use mekanism ores mod for ore compatibility and energy converters from energy converters mod or rf to he converters from hbm (no idea, if it works with other energy units besides rf)

**Comment by MiniRaptor** [comment]
> use mekanism ores mod for ore compatibility and energy converters from energy converters mod or rf to he converters from hbm (no idea, if it works with other energy units besides rf)

Sure i can use those mods, but it would be really good if mods will compat to each other by default

**Comment by Alcatergit** [comment]
Unidict solves that - use that and overwrite lines 222 in its config so that it looks like this.

S:ownerOfEveryThing <
        minecraft
        hbm
        thermalfoundation
        substratum
        ic2
        mekanism
        immersiveengineering
        techreborn
     >
