### ISSUE TITLE
Bug: Incorrect TU/t values for specific solid firebox fuels

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#254]
The following items have incorrect (the default 100TU/t) firebox output values per tick:

- Solid fuel block (Should be 300TU/t)
- Every Presto log/Boosted presto log item/block (Should be 300TU/t)
- Dense coal cluster (Should be 200TU/t)

**Comment by Alcatergit** [comment]
Fixed
