### ISSUE TITLE
Gerald does not spawn tektite and lava.

### ISSUE THREAD

**Issue by ElPudgino** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#258]
Gerald explosion doesnt leave lava and tektite which is required for osmiridium.

**Comment by CapitalismWouldveWorked** [comment]
This feature isn't implemented, for now you get osmiridium from the asteroid mining ship from processing tektite powder.

**Comment by Alcatergit** [comment]
Yes you shoot up Gerald and use its sat chip in the sat landing pad of the mining ship. Then you get Tektite.
