### ISSUE TITLE
[bug] Ore Acidizer And Lubricant Problem

### ISSUE THREAD

**Issue by kpstool** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#260]
Version:1.12.2-1.9.8

Problem 1:Lubricant can't fill in Canister ,the Canister texture and name have some error.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/61050435/0406e90e-5cbf-4c7c-8158-5d766e119c62)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/61050435/5fc2cda3-34d1-4dd7-9990-9a080adbbbfc)

Problem 2:Ore Acidizer can't input sulfuric acid.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/61050435/9c74e8fa-ff95-4791-83b4-2868e600864d)

**Comment by Alcatergit** [comment]
1. You can use a Barrel to automate that.
2. There propably are 2 ore more Sulfuric Acids in your modpack and that is the wrong one.
