### ISSUE TITLE
No option to turn off black lung in the config

### ISSUE THREAD

**Issue by Hat-Master** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#266]
I don't know if that option was in the original 1.7.10 mod, but it was in the 1.12.2 reloaded one. Just annoying. Not everyone can handle coal dust at such early game. Would it be possible to add the option to disable it?

**Comment by CapitalismWouldveWorked** [comment]
There is an option to disable it in the recent release, check line 56 of the config. It gets rid of black lung, but not the visual effect.

Also, coal dust early game can be handled with makeshift gas mask filters (for any gas mask) and dry masks made from cloth.
