### ISSUE TITLE
QOL: Sand -> Silicon Shredding recipe

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#267]
TLDR: HBM 1.7.10 did it, we can too.

Silicon is essential for refined storage, but the only way to get it without other tech mods is smelting quartz. Which is hard to get enough of towards mid-game (Based on my 70-hour HBM 1.12.2 world).

Tech mods like Mekanism and Nuclearcraft have this recipe specifically for Refined Storage users. But of that means adding them to a modpack, and their balance is completely different from HBM.

Adding this recipe will just save the effort of adding CraftTweaker just add a single recipe for everyone.

**Comment by Alcatergit** [comment]
Sand -> Silicon is a bit too cheap. And there are Quartz BedrockOre Nodes in the Nether so quartz should be plentyfull.
But ill add support for shredding ae2 crystals in the shredder using oredict recipes.
