### ISSUE TITLE
Compatibility: JEI Machine Recipes unviewable with JAOPCA

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#268]
I'm unsure what's causing this, but in large modpacks (120+) the JEI recipe viewer doesn't allow the viewing of some HBM machine recipes (anvils, acidizers, etc).

I can't right-click the recipe to view them and I can't see them in the "Show all recipes" tab.

The recipes still work, but it's annoying having to guess which acid to use on which ore.

Edit: It's JAOPCA's fault

**Comment by Shibva** [comment]
Not sure if this is related or not but there is an issue regarding JEI compat as some of the renders (like spiny lights) don't show up in their menu anymore and is rendered invisible; same goes for some of the pre-made custom missiles as well

**Comment by CapitalismWouldveWorked** [comment]
**_Edit: Ignore this comment. This was the wrong modpack I listed_**

Testing with just JEI and HBM seems to have no issues. The most likely culprit is the variety of mixinbooter mods that affect JEI loading.

Here's the list of mods used in a smaller pack with the same issues:
  [✔️] !configanytime-1.0.jar
  [✔️] !mixinbooter-8.8.jar
  [✔️] !Red-Core-MC-1.7-1.12-0.5.1.jar
  [✔️] [1.12.2]bspkrscore-universal-8.0.1.jar
  [✔️] _supermartijn642corelib-1.1.15-forge-mc1.12.jar
  [✔️] AIReducer-1.12.2-0.3.0.jar
  [✔️] alcatrazcore-1.0.4.jar
  [✔️] Alfheim-1.1.1.jar
  [✔️] AutoRegLib-1.3-32.jar
  [✔️] base-1.12.2-3.14.0.jar
  [✔️] BetterFps-1.4.8.jar
  [✔️] CD4017BE_lib-1.12.2-6.5.1.jar
  [✔️] censoredasm5.14.jar
  [✔️] Chisel-MC1.12.2-1.0.2.45.jar
  [✔️] Chunk+Pregenerator-V1.12-2.5.7.jar
  [✔️] Controlling-3.0.12.2.jar
  [✔️] coroutil-1.12.1-1.2.37.jar
  [✔️] CTM-MC1.12.2-1.0.2.31.jar
  [✔️] Cucumber-1.12.2-1.1.3.jar
  [✔️] CyclopsCore-1.12.2-1.6.7.jar
  [✔️] EntityCulling-1.12.2-6.4.1.jar
  [✔️] FastFurnace-1.12.2-1.3.1.jar
  [✔️] Forgelin-1.8.3.jar
  [✔️] geckolib-forge-1.12.2-3.0.31.jar
  [✔️] Hwyla-1.8.26-B41_1.12.2.jar
  [✔️] InGameInfoXML-1.12.2-2.8.2.94-universal.jar
  [✔️] InventoryTweaks-1.63.jar
  [✔️] jei_1.12.2-4.15.0.291.jar
  [✔️] LagGoggles-1.12.2-5.9-140.jar
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal.jar
  [✔️] MouseTweaks-2.10.1-mc1.12.2.jar
  [✔️] MTLib-3.0.7.jar
  [✔️] mysticallib-1.12.2-1.13.0.jar
  [✔️] NetherPortalFix_1.12.1-5.3.17.jar
  [✔️] NTM-Extended-1.12.2-1.9.8.jar
  [✔️] OptiFine_1.12.2_HD_U_G5.jar
  [✔️] particleculling-1.12.2-v1.4.1.jar
  [✔️] performant-1.11.jar
  [✔️] Placebo-1.12.2-1.6.1.jar
  [✔️] Quit-Forge-1.12.2-1.0.1-mixinless.jar
  [✔️] RenderLib-1.12.2-1.3.3.jar
  [✔️] SilentLib-1.12.2-3.0.14+168.jar
  [✔️] startuptimer-1.0.1.jar
  [✔️] supermartijn642configlib-1.1.8-forge-mc1.12.jar
  [✔️] TickCentral-3.2.jar
  [✔️] torohud-1.12.2-5.jar
  [✔️] UniDict-1.12.2-3.0.10.jar
  [✔️] UniversalTweaks-1.12.2-1.8.0.jar
  [✔️] vintagefix-0.3.1.jar
  [✔️] WanionLib-1.12.2-2.9.jar
  [✔️] WrapUp-1.12-1.1.3.jar

**Comment by CapitalismWouldveWorked** [comment]
If it helps, I would also like to add that testing with the HBM 1.6.9A (TheOriginalGolem fork) doesn't have this issue for some reason. The same mods I listed were used.

I'll get around to doing more testing later on with just the mixin-related mods and prior NTM Extended versions since I don't remember this being an issue in earlier versions of this fork.

**Comment by CapitalismWouldveWorked** [comment]
The culprit is the mod JAOPCA, removing that mod fixes this issue. I don't know the specific cause nor how to fix it, JAOPCA isn't very fond of HBM according to the config comments and made compatibility based on TheOriginalGolem fork.

I don't even think it's worth it to fix this issue as it seems this mod causes this issue with other mods recipes. I'll leave this up for you to decide.
