### ISSUE TITLE
Bug:Game crashes when teleporting (java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]})

### ISSUE THREAD

**Issue by NEFirefox** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#270]
The Crash-Report:
https://pastebin.com/DZzAxPMN

I tried changing the version of the mod **BDLib** and **Pressure**, but it throws the same exception.
so i decided to put this issue under **NTW**.

Description:
it always happens when some pipe system(mk2?) get loaded and then you attempt to use someting to teleporting.
the game try to render the block *minecraft:air*'s EnumFacing while unloading the chunks

Suspected Mods: 
BD Lib (bdlib), Pressure Pipes (pressure), HBM's Nuclear Tech - Extended Edition (hbm)

**Comment by Alcatergit** [comment]
Fixed - will be in next update
