### ISSUE TITLE
Bug: RAD overdose kill method bypasses Ghostly Shape from Corail Tombstone

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#271]
The effect added by Corail Tombstone called Ghostly Shape is applied when the player respawns. It gives them temporary invisibility to mobs and immunity to all forms of damage until they interact with containers, hit an entity, or the effect times out.

This works for everything except for the RAD overdose as it will somehow bypass the damage and kill the player when it shouldn't.

This creates an issue where some mods or custom CT scripts (in my case) will kill the player but as a result of the effect will prevent the event that damages the player to not fire and create problems.

Solution: allow for the effect to suppress the instant kill for as long as the effect is present or have the effect also give the player a 100% RAD resistance for as long as the effect is on the player; this effect cannot be acquired through other means other than the player respawning

**Comment by Shibva** [comment]
Or you can do a third option, and just remove all effects before being killed


At a side note I did manage to make a workaround for something that this is breaking; just to let you know but this is still an issue

**Comment by Shibva** [comment]
To add context to the comment above; this is not a fork, it's a CT script I made towards improved soulbound mechanics though data manipulation that ultimately boils down to "soulbound item stays in slot it was in"

If you wanna see it let me know. This is how I came across this issue

**Comment by Shibva** [comment]
This issue no doubt is caused by the attack and kill method that the RAD system does; adding some method to check for it can work; its interesting that it manages to brute-force past it lol

I do have a CT script that manages to bypass this thanks to it creating a custom damage type that I am able to detect and cancel the damage event; if you wanna see it let me know :P

**Comment by Shibva** [comment]
@Alcatergit the dev for Corail is looking into this on their end as well; is there anything that would be useful to know? I am aware that this thing that kills you can kill you in creative; so I am wondering if there are `setDead` or `setHealth` methods being used; I cant remember and might need some resources on some of these things just in case. I was informed by him and in turn infrormed him about some of the mechanics that I feel would be useful to know; like the fact that the thing that executes you over 1000 RADs is relentless and will repetitively will try to kill you over and over again

feel free to hop in the other report above if ya want :D

**Comment by Shibva** [comment]
nothing can be done on the other dev's side. They tried something and it didn't work. It was because of [this line](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/blob/342a50ecf193103e33d7fe2b889e36a445e751ed/src/main/java/com/hbm/handler/RadiationSystemNT.java#L414). It is blocking the 1000 points of damage but the contingency `setHealth(0)` is being fired

if this issue is going to be fixed, it needs to be done on this end by adding a check . Presumably checking for the effect `tombstone:ghostly_shape`

**Comment by Alcatergit** [comment]
Added "tombstone:ghostly_shape" to default mob rad immunity config.
