### ISSUE TITLE
He to RF Converters eating up power forever

### ISSUE THREAD

**Issue by Hat-Master** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#276]
While messing around I noticed that if you connect a HE to RF converter to any power source it doesn't reach a power storage cap, it just keeps eating all of it up forever. I can connect millions of machines to a power source and no issues will occur but as soon as put down a converter which isn't even connected to any RF machine, it starts eating all of it up. I tried setting up a RF to HE converter next to the HE to RF converter so that it gets back the power its taking but, but it still eats power. I hope I'm making sense here. What can I do?

**Comment by ntmleafia** [comment]
doesn't happen on 1.9.7 (it used to happen on Reloaded)
it's time to update ur mod

**Comment by Hat-Master** [comment]
I'm on 1.9.8, can't really update it any further

**Comment by Hat-Master** [comment]
I seem to have found a way to fix the issue. Rather than connecting the converters directly to my power source, I can instead connect an energy storage block to the power source and then the converters to the storage block. That seems to fix everything.
