### ISSUE TITLE
1.12.2 DFC not working, also render issues.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#28]
For some reason in the 1.12.2 version the Dark Fusion Core doesn't work... The dfc beam emitter, receiver, stabilizer, and fuel injector work as intended, but the stabilizer's beams don't render properly, only showing the start and end points with the middle of the beam being invisible and the beam being black, blue, and red. As for the core, it isn't consuming any fuel, and it doesn't add any energy to the receiver...
![Screenshot 2022-12-28 125946](https://user-images.githubusercontent.com/60857805/209859943-e69f1d5f-f6ac-4f30-bb2c-e23f9b5eae8e.png)

**Comment by xenoulexi** [comment]
Also I have a problem where for some reason RBMK steam channels don't accept water if I put a cover pannel on them, and I need to use the Thermal Series servos to force the steam out of the channels because the channels don't output the steam naturally.

**Comment by xenoulexi** [comment]
And with the normal multiblock reactor, none of the item transport methods I have, be they Thermal Itemducts, Mekanism Logistical Transporters, or even Immersive Engineering conveyors can actually connect to the fuel input and waste output blocks, meaning I cannot automate them.

**Comment by Alcatergit** [comment]
normal multiblock reactor: Just put chests on the input/output ports

**Comment by Alcatergit** [comment]
RBMK steam channels: use RBMK Steam connectors

**Comment by Alcatergit** [comment]
Dark Fusion Core: Make sure to put a core inside the core. Stabelizers need Stabelizing lenses

**Comment by xenoulexi** [comment]
I'm still having problems with the DFC

![Screenshot 2023-01-07 165828](https://user-images.githubusercontent.com/60857805/211173349-2879fc6d-90d9-4664-8f5d-f8689aa2e6f0.png)
![Screenshot 2023-01-07 165839](https://user-images.githubusercontent.com/60857805/211173350-d9201c94-5468-4735-b918-a35cde55f32e.png)
![Screenshot 2023-01-07 165851](https://user-images.githubusercontent.com/60857805/211173351-0295ed8e-c704-4763-9443-8b06004d21b1.png)
![Screenshot 2023-01-07 165904](https://user-images.githubusercontent.com/60857805/211173354-c6266a67-382e-45fe-8de2-fed5cf5a2d09.png)
![Screenshot 2023-01-07 165928](https://user-images.githubusercontent.com/60857805/211173355-7538ac1e-1372-424e-90c2-8ad046a7b884.png)

**Comment by ntmleafia** [comment]
fluids added by mekanism doesn't seem to support ntm, and they are likely to conflict and even replace fluids in your world, making your DFC unusable even if it used to work. try fluids that are obiviously from ntm, such as balefire and antischrabidium

if that still doesn't fix, try using schrabidium catalyst

(me replicating your issue)
![image](https://user-images.githubusercontent.com/121738096/212538121-166742d7-f90b-4fde-8721-40d1957bf485.png)
