### ISSUE TITLE
Bug: Game crashes when trying to insert fluid into a tank with gregtech pipes

### ISSUE THREAD

**Issue by Vidarin** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#281]
If I try to use GT pipes with HBM machines the game crashes and I'm unable to start the world again. (It works perfectly fine with hbm pipes and GT machines) 

Heres the full log:

[latest.log](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/14072599/latest.log)

**Comment by Alcatergit** [comment]
Fixed. Will be in the next update.
