### ISSUE TITLE
some of doors should be made back manually controllable again

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#282]
so in ntm extended you can't manually open doors and instead you have to give them redstone signal which makes sense for heavy blastdoors etc
but it kinda makes no sense how obiviously unpowered doors like small hatch and water door also aren't manually openable

**Comment by Alcatergit** [comment]
They can be manually opened via lock and key. So if you want to open the doors via right click you just need to lock the door and use the key to open it.

**Comment by ntmleafia** [comment]
Oh so that was an intentional feature

**Comment by ntmleafia** [comment]
I thought that was bug lol
