### ISSUE TITLE
Crafttweaker, assembler unable to utilize oredictionary

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#283]
I have attempted to use oredict in some recipes and get errors back. looking into the documentation it is only meant to handle IItemstack[], it would be nice if it was implemented to work for oreDictionary. According to the error, the method of using an oreDict falls under a IIngredient 
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/bdee9088-08a8-4711-a18e-8b49da69bf60)

**Comment by Alcatergit** [comment]
Yeah OreDict ingredients are not supported. Use the actual item instead

**Comment by Shibva** [comment]
ah, I was thinking it should have been, because there are a few NTM recipes that use oreDictionary and I was modifying the recipe; but alas I was unable to replace it with the oreDictionary used
