### ISSUE TITLE
(suggestion) rbmk fuel rod outgoing flux

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#284]
Sometimes I wish if I could directly see how much flux a fuel rod is emitting instead of having to check incoming flux on surrounding fuel rods or doing math everytime

**Comment by Alcatergit** [comment]
The RBMK Console shows exaclty that

**Comment by ntmleafia** [comment]
OH cool! thanks for telling me
Extended Edition is always a VERY good revival of 1.12.2 port!
