### ISSUE TITLE
QoL bugfix: Change default bedrock ore list for overworls into whitelist only by default

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#286]
This is in regards to an issue I've noticed regarding bedrock ores handeling being broken for whatever reason (I.e: steel ore is a thing for god knows why] and think it would be best to change the default generated config to be a whitelist of proper ores as a default instead of trying to blacklist them all whenever a new valid ore material is added. It's not a perfect fix but is an improvement that I would believe take minimal work

Extra:
It would also be nice if you could somehow assign a texture for these bedrock ores (using bedrock as default) in each dim to allow for them to "blend in" more with the worlds own floor of bedrock-equivalent blocks by providing the name of the block you want it to look like (great for things like the Betweenlands where they have a different yet bedrock type of floor)

**Comment by Shibva** [comment]
As for the first bit, this seems like a simple enough task for someone with a flimsy understanding of Java

All I just need todo is modify the default string values and it should be good

Expect a merge request with this fix :)

**Comment by Alcatergit** [comment]
It is easier to blacklist the ores one does not want compared to whitelisting all the wante ones.
That is because the amount of ores we want is greater then the amount of ores we don't want.
The new default config will have a much bigger blacklist of unwanted ores covering many.
If you know any more unwanted ore let me know. oreSteel will be in the blacklist.

**Comment by Shibva** [comment]
oh; wish I saw this sooner, I just finished the change to whitelist in a merge request XD

I may not know java, but this was trivial todo lel

there goes an hour of my time
