### ISSUE TITLE
[Render Bug] Power armor energy HUD does not render when using third-party Heath UI

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#288]
This has been a bug for a while and I thought I had reported this or a report existed on it; however, going back through the reports here I see that I either didn't or it became lost to time.

Anyhow, When you wear a full set of power armor, 4 bars above the armor UI appear to indicate the armor's charge level. I have discovered that this is not the case when you are using something else to alter the UI display elements in regards to Health and/or Armor (armor overlay changes are untested but could be likely)

This issue occurs when you use a mod like Colorful Health Bar and/or Scaling Health where the HP overlay is modified to have the HP overlap with an alternate color instead of stacking on top of one another. For whatever reason, this change breaks the rendering element of the Power Armor's Battery UI. 

To Reproduce: Install one of the following mods
- Scaling Health
- Colorful Health Bar
- Or both (note: UI elements of SH will override CHB, configure accordingly to disable SH healthbar modifications

Then start up the game and equip a full set of power armor (doesn't matter what one, as long as its a power armor)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/fd6fdb67-0f3e-4243-9bde-ca2d7fb4ca45)
(mind the mess, the image is intended to show the missing UI element while confirming a full set of power armor (t-45) equipped; there are other things I have equipped that add extra visuals so ignore the mess that is myself [yes, I am aware I look ridiculous])

**Comment by Alcatergit** [comment]
1.12.2 does not have the charge bars in the first place lol

**Comment by Shibva** [comment]
oh, I thought it was XD
