### ISSUE TITLE
(suggestion) automated stamp shaper

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#290]
NTM's press stamps are limited. They eventually break.
Press stamps are the only template-folder-made thing that eventually breaks as I believe.
Have to create new one. A blank one. Normal crafting which bunch of other mods support automation.
But the machine template folder. It's a handheld item with it's own GUI.
Always has to be done by player.
Wish if you could automate that.

**Comment by ntmleafia** [comment]
Espicially the wire stamp; HBM's wires are not compatible with other mods. And it probably won't be, since HBM makes 16 wires from 1 ingot, and Immersive Engineering makes only 2 cables from a ingot.
So I have to use HBM press machines.

**Comment by Alcatergit** [comment]
The Desh Stamps have infinite durability and never break. So you can use those in automation of recipe
