### ISSUE TITLE
NPE crash

### ISSUE THREAD

**Issue by whatsapp2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#30]
Got this crash report. The world was working fine before latest update
[crash-2022-12-29_14.16.51-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/10321917/crash-2022-12-29_14.16.51-server.txt)

**Comment by Njet75** [comment]
Same here.

**Comment by dazadazu** [comment]
Yeah, me too.

**Comment by luxvent** [comment]
As i described in #29 new dimension config update conflicts with some mods wich add their own dimensions(XU2, Adv Rocketr, Aroma Dim World and others). In this case i think the problem in Spatial Cell Dim in AE2. Waiting for fix
