### ISSUE TITLE
Lava temperautre description

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#304]
![05b686817d1345c2947957bc8266cf97](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/121738096/6c645309-e278-4bff-bcb8-ea84b0d8f5da)
aren't rocks supposed to melt at 1300? (or it's just that I'm stupid at geology lol)

**Comment by Alcatergit** [comment]
Looks like the mod that fluid is from set the tempature in °C but game handles it as °K

**Comment by ntmleafia** [comment]
oh wow, 1300-273 was exactly this lol
