### ISSUE TITLE
some strange broken things and bugs

### ISSUE THREAD

**Issue by username90001** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#31]
there are 2 ressourses pages like resourses and parts and just ressourses and also it has 2 s
infinite fluid tank not working
singularity screwdriver useless
new fusion reactor from 1.7.10 broken  plasma heater dont want to get fluid indenifier of deuterium tritium and other things
edit it can automaticaly but still remove fluid indenifier from plasma heater gui
when u place old fusion reactor using structure wand u stuck inside of it
super conducting magnet looks likes strange from up
there are 2 infinite energy batteries
gerald impossible to craft
fire box and steel furnance looks likes strange in inventory
ams and its explosion at diferent places i cant explain it normaly

**Comment by Alcatergit** [comment]
Good find: The fluid template slots of the plasma heater will be removed in the next update

**Comment by Alcatergit** [comment]
Gerald is craftable but the recipe is hidden in JEI

**Comment by username90001** [comment]
then how we are supposed to craft gerald

**Comment by luxvent** [comment]
Check official [Wiki](https://ntm.fandom.com/wiki/HBM%27s_Nuclear_Tech_Wiki) or check usages in jei for Radiation Coin(or whatever this thing called, i can`t remember)

**Comment by username90001** [comment]
ok
