### ISSUE TITLE
Bug: Bedrock Ore not working properly

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#318]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/0a4b2b77-0d24-4710-8f07-a1bf87c3b182)
As you can see, bedrock ore is not working properly...

**Comment by Alcatergit** [comment]
Fixed it

**Comment by Shibva** [comment]
This is a duplicate of another issue for the record #309
