### ISSUE TITLE
New config options?

### ISSUE THREAD

**Issue by Ashen-sysadmin** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#32]
Could a few config options for disabling in-jokes be added? 

Things like the "press O to duck" feature are really cool, but Modpack makers might want the ability to disable them for tonal reasons.

**Comment by Alcatergit** [comment]
You can just unset the "O" keybind so it wont be triggered

**Comment by Ashen-sysadmin** [comment]
Seriously? Key binds are on the user side of the equation. 

Modpack developers can't use mods like these of they are unable to disable disruptive memes features.
