### ISSUE TITLE
(QoL/Bug) Can we please do something about snow...

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#321]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/b6d6a9f1-482b-4e00-bca2-af25ff838158)
I don't like having to put lights everywhere to stop the snow from spawning on top of blocks which clearly don't visually support it.

**Comment by Alcatergit** [comment]
Fixed it
