### ISSUE TITLE
All existing chemplant templates are changed to chem.BAD_RECIPE after 2.0.1 update

### ISSUE THREAD

**Issue by Xreturns** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#327]
title says it all. if a chemplant template was made before 2.0.1, it becomes a bad recipe. new ones work fine.

**Comment by Alcatergit** [comment]
just recycle the ones with missing textures. I switched to the id based system that 1.7 uses. That way we get the missing textures once now and then never again.

**Comment by Xreturns** [comment]
alright.
