### ISSUE TITLE
Re: CT implimentation Improvment: questions

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#329]
continuing on #283; I am curious on why it was set up to use IItemstrack instead of IIngredient which would include support for ore dictionary stuff; is there a specific reason for why? if its because of possible issues where it relies on IItemStack, I would like to note in case its not known that all functions in IItemStack in the documentation can extend to IIngredient

so overall I'm just curious at this point

**Comment by Alcatergit** [comment]
Could not find the documentation for IIngredient for 1.12.2 CT. I pretty much reverseengineered it by searching IItemStack uses in other open source mods.
