### ISSUE TITLE
smaller explosive devices seems to be dealing nuclear explosion damage?

### ISSUE THREAD

**Issue by Potatoo-Cake** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#334]
small bombs like explosives charges and multi purpose bomb explode with nuclear explosion damage
it can basically kill anything in its range despite being just a yknow, conventional bomb
(was using version 2.0.0)

oh also it seems like anti-tank mines are killing gods which im not entirely sure is that a good thing

**Comment by Potatoo-Cake** [comment]
most of the missiles and grenades too

**Comment by Alcatergit** [comment]
Fixed
