### ISSUE TITLE
All the EMP related items doesn't work and cause crashes

### ISSUE THREAD

**Issue by Potatoo-Cake** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#336]
Emp gun crashes when its explosion hit any machine
[crash-2024-02-17_15.10.07-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/14318030/crash-2024-02-17_15.10.07-server.txt)
Emp devices crash when detonated
[crash-2024-02-17_15.12.27-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/14318033/crash-2024-02-17_15.12.27-server.txt)
Emp missiles seem to do nothing when detonated

**Comment by 3114396pig** [comment]
add the mod [redstone flux](https://www.curseforge.com/minecraft/mc-mods/redstone-flux) will fix it
it is because emp related methods use class IEnergyProvider, whitch is an interface at package cofh.redstoneflux.api
use he->rf converter will also cause the same problem for the same reason

**Comment by Alcatergit** [comment]
Fixed
