### ISSUE TITLE
Why Schrabidium armor have only 90% radiation resistance

### ISSUE THREAD

**Issue by OppaiHacker** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#339]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/89047121/8fb883be-4152-45bd-9797-4fa0b393e0a8)

Why Schrabidium armor have only 90% radiation resistance

**Comment by Alcatergit** [comment]
Fixed
