### ISSUE TITLE
Crash with Energy Control

### ISSUE THREAD

**Issue by luxvent** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#34]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods:
[hbm-A-1.12.2-1.8.4b.jar](https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-alcater-edition/files/4280765)
[EnergyControl-1.12.2-0.3.1.jar](https://www.curseforge.com/minecraft/mc-mods/energy-control/files/3829524)

[Crash](https://gist.github.com/Zephyriumtdw/76824ba488cde0cb8d61bb966866c8de)

Crash happens when i'm trying to create or join the world. I don't know is it NTM's fault or EC's but on version hbm-A-1.12.2-1.8.3b.jar there is no crashes.

**Comment by Alcatergit** [comment]
Good find - will be fixed in the next update
