### ISSUE TITLE
Add a way to disable Mob Gear

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#340]
Could you add someway to toggle if mobs spawn with equipment? 

Maybe with config option? Like in this Mod: https://www.curseforge.com/minecraft/mc-mods/hbm-fixes

**Comment by Potatoo-Cake** [comment]
config\hbm\hbm_dimensions.cfg > 06.05_mobGear
donno why it's in dimensions config tho

**Comment by ghost** [comment]
oh ok thats why i was confused Thxx for the reply!
