### ISSUE TITLE
Meteors

### ISSUE THREAD

**Issue by MixasFox** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#341]
Do meteors exist on the latest version? I have them turned on everywhere except special meteors in config, but in all 4 days of playing not a single one fell. Has the rarity of meteors been reduced in ntm extended? Because in the reloaded version they crashed almost 2 times in one game day.

**Comment by MixasFox** [comment]
I beat ender dragon and i need meteorites for progression but still no meteors fell. Have someone got the same issue or i am that unlucky? I find it strange because when i've been playing on a server with my friend(using hbm reloaded) meteors fell once in 2 days or something like that, sometimes few of them in one day.

**Comment by MixasFox** [comment]
Also i wanted to add that i played with hbm reloaded in my world before i discovered extended version and then used it instead. Maybe that could be the issue?

**Comment by Alcatergit** [comment]
Had a type which multiplied the default value by 0. Got it fixed. Go into config/hbm/hbm_dimensions.cfg and change the entry for overworld:

S:05.01_meteorStrikeChance <
        0:60000

**Comment by MixasFox** [comment]
Thank you.
