### ISSUE TITLE
no missile explosion sound

### ISSUE THREAD

**Issue by VALERIMAK253** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#344]
after the new update there is no missile explosion sound, including the CL missile bombs
and the IC missiles is first igniting the surroundings, then exploding so no fire remains
also, the EMP missiles is crashing the game when detonating

**Comment by Luftwafflez** [comment]
Are you using a mod that disables thunder/lightning sounds? The new ExplosionMk5 code uses the thunder sound effect, which certain mods/modpacks disable for whatever reason. badwithernocookiereloaded is a common one. You can usually reenable it in the relevant mod's config file. 

As far as the EMP is concerned, what other power mods are you running? Submitting a crash report would help.

**Comment by Alcatergit** [comment]
Fixed explosion sounds for very small explosions. Will be in next update.
