### ISSUE TITLE
Crash 1.8.4.c

### ISSUE THREAD

**Issue by dazadazu** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#35]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Why did you do that?

Time: 2023-01-01 12:23:35 PST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.util.ConcurrentModificationException
    at java.util.WeakHashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.WeakHashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.item.crafting.Ingredient.invalidateAll(Ingredient.java:103)
    at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:587)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
    at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_341, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 8604861784 bytes (8206 MB) / 12047613952 bytes (11489 MB) up to 18745917440 bytes (17877 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6000m -Xmx20112m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 58 mods loaded, 58 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State   | ID                 | Version                | Source                                            | Signature                                |
       |:------- |:------------------ |:---------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA  | minecraft          | 1.12.2                 | minecraft.jar                                     | None                                     |
       | LCHIJA  | mcp                | 9.42                   | minecraft.jar                                     | None                                     |
       | LCHIJA  | FML                | 8.0.99.99              | forge-1.12.2-14.23.5.2860-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJAE | forge              | 14.23.5.2860           | forge-1.12.2-14.23.5.2860-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA  | creativecoredummy  | 1.0.0                  | minecraft.jar                                     | None                                     |
       | LCHIJA  | mixinbooter        | 7.0                    | minecraft.jar                                     | None                                     |
       | LCHIJA  | foamfixcore        | 7.7.4                  | minecraft.jar                                     | None                                     |
       | LCHIJA  | tickcentral        | 3.2                    | TickCentral-3.2%20(1).jar                         | None                                     |
       | LCHIJA  | WarpDriveCore      | 1.12.2-1.5.28.SNAPSHOT | minecraft.jar                                     | None                                     |
       | LCHIJA  | aireducer          | 0.3.0                  | AIReducer-1.12.2-0.3.0.jar                        | None                                     |
       | LCHIJA  | creativecore       | 1.10.0                 | CreativeCore_v1.10.65_mc1.12.2.jar                | None                                     |
       | LCHIJA  | ambientsounds      | 3.0                    | AmbientSounds_v3.1.7_mc1.12.2.jar                 | None                                     |
       | LCHIJA  | betterf3           | 1.12.2-1.0             | betterf3-1.12.2-1.0.jar                           | None                                     |
       | LCHIJA  | betternether       | 0.1.9.4                | BetterNetherRotN-1.12.2-0.1.9.4.jar               | None                                     |
       | LCHIJA  | betterthirdperson  | 1.8.0                  | BetterThirdPerson-Forge-1.12.2-1.8.0.jar          | None                                     |
       | LCHIJA  | biomeheighttweaker | 1.12-0.9               | biomeheighttweaker-1.12-0.9.jar                   | None                                     |
       | LCHIJA  | clumps             | 3.1.2                  | Clumps-3.1.2 (2).jar                              | None                                     |
       | LCHIJA  | codechickenlib     | 3.2.3.358              | CodeChickenLib-1.12.2-3.2.3.358-universal (2).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA  | coralreef          | 2.0                    | CoralReef-2.5-1.12.2 (2).jar                      | None                                     |
       | LCHIJA  | extendedrenderer   | v1.0                   | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHIJA  | coroutil           | 1.12.1-1.2.37          | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHIJA  | configmod          | v1.0                   | coroutil-1.12.1-1.2.37.jar                        | None                                     |
       | LCHIJA  | customnpcs         | 1.12                   | CustomNPCs_1.12.2-(05Jul20).jar                   | None                                     |
       | LCHIJA  | dynamictrees       | 1.12.2-0.12.1          | DramaticTrees-1.12.2-0.12.1.jar                   | None                                     |
       | LCHIJA  | orelib             | 3.6.0.1                | OreLib-1.12.2-3.6.0.1 (2).jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA  | dsurround          | @VERSION@              | DynamicSurroundings-1.12.2-3.6.3.jar              | None                                     |
       | LCHIJA  | renderlib          | 1.1.10                 | RenderLib-1.12.2-1.1.10 (1).jar                   | None                                     |
       | LCHIJA  | entityculling      | 6.2.5                  | EntityCulling-1.12.2-6.2.5.jar                    | None                                     |
       | LCHIJA  | fbp                | 0.5                    | fbp-0.5.jar                                       | None                                     |
       | LCHIJA  | foamfix            | @VERSION@              | foamfix-0.10.15-1.12.2.jar                        | None                                     |
       | LCHIJA  | forgelin           | 1.8.4                  | Forgelin-1.8.4 (2).jar                            | None                                     |
       | LCHIJA  | fpsreducer         | mc1.12.2-1.17          | FpsReducer-mc1.12.2-1.17.jar                      | None                                     |
       | LCHIJA  | jei                | 4.24.2                 | HadEnoughItems_1.12.2-4.24.2.jar                  | None                                     |
       | LCHIJA  | hbm                | hbm-A-1.12.2-1.8.4c    | hbm-A-1.12.2-1.8.4c.jar                           | None                                     |
       | LCHIJA  | waila              | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2 (2).jar                   | None                                     |
       | LCHIJA  | laggoggles         | 1.12.2-5.8-132         | LagGoggles-1.12.2-5.8-132 (1).jar                 | None                                     |
       | LCHIJA  | loliasm            | 5.6                    | loliasm-5.6.jar                                   | None                                     |
       | LCHIJA  | memorycleaner      | 1.4                    | memorycleaner-1.4.jar                             | None                                     |
       | LCHIJA  | nei                | 2.4.3                  | NotEnoughItems-1.12.2-2.4.3.245-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA  | nothirium          | 0.1.10-beta            | Nothirium-1.12.2-0.1.10-beta.jar                  | None                                     |
       | LCHIJA  | particleculling    | v1.3                   | particleculling-1.12.2-v1.3.1.jar                 | None                                     |
       | LCHIJA  | patchouli          | 1.0-23.6               | Patchouli-1.0-23.6.jar                            | None                                     |
       | LCHIJA  | rawinput           | 1.4.0                  | rawinput-1.4.0.jar                                | None                                     |
       | LCHIJA  | rep                | 1.0.0                  | RealisticExplosionPhysics-1.12.2-1.0.0.jar        | None                                     |
       | LCHIJA  | regrowth           | 0.0.0.5                | Regrowth-1.12.2-0.0.1.1 (1).jar                   | None                                     |
       | LCHIJA  | resourceloader     | 1.5.3                  | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA  | jeid               | 2.0.2-SNAPSHOT         | RoughlyEnoughIDs-1.12.2-2.0.2-CubicCompat.jar     | None                                     |
       | LCHIJA  | snowrealmagic      | 0.6.2                  | SnowRealMagic-1.12.2-0.6.2.jar                    | None                                     |
       | LCHIJA  | startuptimer       | 1.0.0                  | startuptimer-1.0.1.jar                            | None                                     |
       | LCHIJA  | twilightforest     | 3.11.1021              | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
       | LCHIJA  | universaltweaks    | 1.12.2-1.2.0           | UniversalTweaks-1.12.2-1.2.0.jar                  | None                                     |
       | LCHIJA  | warpdrive          | 1.12.2-1.5.28.SNAPSHOT | WarpDrive-1.12.2-1.5.28.jar                       | f7be6b40743c6a8205df86c5e57547d578605d8a |
       | LCHIJA  | weather2           | 2.8.4-indev-b          | Weather2Remastered-1.12.2-2.8.4-indev-b.jar       | None                                     |
       | LCHIJA  | wgblockreplacer    | 2.3.3+1.12.2           | WorldGen-Block-Replacer-2.3.3+1.12.2 (1).jar      | None                                     |
       | LCHIJA  | llibrary           | 1.7.20                 | llibrary-1.7.20-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA  | midnight           | 0.3.5                  | MidnightDOKU.jar                                  | None                                     |
       | LCHIJA  | phosphor-lighting  | 1.12.2-0.2.7           | phosphor-forge-mc1.12.2-0.2.7-universal.jar       | None                                     |
       | LCHIJA  | thebetweenlands    | 3.9.1                  | TheBetweenlands-3.9.1-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): Startup Timer (startuptimer-1.0.1.jar)
                                        
                                      midnight (MidnightDOKU.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4 (2).jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-1.12.2-2.0.2-CubicCompat.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      WarpDriveCore (WarpDrive-1.12.2-1.5.28.jar)
                                        cr0s.warpdrive.core.ClassTransformer
                                      TickCentral (TickCentral-3.2 (1).jar)
                                        com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer
                                        com.github.terminatornl.laggoggles.tickcentral.RenderManagerTransformer
                                        com.github.terminatornl.tickcentral.asm.BlockTransformer
                                        com.github.terminatornl.tickcentral.asm.ITickableTransformer
                                        com.github.terminatornl.tickcentral.asm.EntityTransformer
                                        com.github.terminatornl.tickcentral.asm.HubAPITransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      NothiriumPlugin (Nothirium-1.12.2-0.1.10-beta.jar)
                                        meldexun.nothirium.mc.asm.NothiriumClassTransformer
                                      Snow! Real Magic! (SnowRealMagic-1.12.2-0.6.2.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.65_mc1.12.2.jar)
                                        
                                      LoliASM (loliasm-5.6.jar)
                                        
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.2.0.jar)
                                        
                                      RenderLibPlugin (RenderLib-1.12.2-1.1.10 (1).jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      MixinBooter (!mixinbooter-7.0.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.2.5.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.56' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
  Patchouli open book context: n/a
  Suspected Mods: Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.56, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: SaxCraft.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 24x AMD Ryzen 9 3900X 12-Core Processor

**Comment by dazadazu** [comment]
In boot up.

**Comment by DNIWE041** [comment]
Forge can't load (it's a mod loader).
How many optimisation mods you have? Try to disable them, maybe loliasm, foam fix. 

Your computer is 3080+ ryzen 3900X+and more than 20gb RAM, are you sure about alot optimisation mods?
