### ISSUE TITLE
[BUG] Crafting with mercury spontaneously generates glass bottles

### ISSUE THREAD

**Issue by Switchamafuck** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#355]
Crafting with mercury in the crafting table creates glass bottles from nothing

https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/164095665/38610232-e1d1-440d-bc1a-9ed18b27fcb8

**Comment by Shibva** [comment]
this seems to be a result of the old recipe and it creating unnecessary mercury

@Alcatergit

**Comment by Alcatergit** [comment]
Fixed
