### ISSUE TITLE
Bug: Concussive explosion force making blocks "fall" through blast resistant blocks

### ISSUE THREAD

**Issue by Huntonius4** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#356]
Concussive force (not sure if it's actually called that, but I mean the radius around an explosive that makes blocks "fall" if they are floating in the air) from explosions such as the Explosive Charge and most Missiles is making blocks "fall" in a larger radius than their actual blast. 
That's to be expected, and it seems to be working as intended on its own. 

However, it doesn't appear to account for reinforced blocks (such as dense stone or concrete) when calculating where a block should "fall".  

For example, if you create a floating platform of concrete, and place some planks in an arrangement so that not all of them will be directly destroyed by the blast, they will "fall" through the platform and onto the ground below. 

A notable exception is with bedrock, which appears to stop blocks from falling through it, and blocks that lack any air tiles below them to "fall" through.

The expected behavior is that all reinforced blocks should be able to block concussive forces (even if only partially), and to act as a 'ground' to blocks "falling" from concussive force.

**Comment by Alcatergit** [comment]
Made the falling of blocks only happen after a certian size threshold
