### ISSUE TITLE
hidden recipe books failing to generate text correctly

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#357]
So, this started with me going to see if I can fix the issue where drops of mercury are returning glass bottles when crafting, so I started trying to hunt it down; I wasn't able to find it, but something caught my interest and to my surprise, I found a hidden recipe and that books I have been finding in the dungeons is this feature; however, after looking at the code, I found that it was supposed to be printing full lines of text but instead:
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/ca91e2cf-8ecb-4151-9f2c-0575a7f0c5f5)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/b1fdf7d4-556a-4c7d-a388-6dd1cab6698e)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/10e8b3f2-58bf-4031-9047-e79f5e5c7f01)

The same goes for the other book I found
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/5a481807-6db2-4e14-89f2-932bdd102b50)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/e13c0542-b5f4-43b6-b4b3-fde820af8edc)

I would link directly but I don't want to make it known to the public, but as the dev you should know what I'm talking about

if you need me to ill be more clear

**Comment by Alcatergit** [comment]
Thank you for the info. I have given fixing the BOOK priority one.

Btw: I fixed the mercury glass bottle duping.

**Comment by Alcatergit** [comment]
Fixed it

**Comment by Shibva** [comment]
@Alcatergit thanks; also go ahead and check my pull request, the name is just a funny thing I'm trying todo since I like it when I see Bob doing it. It takes care of the one bit I forgot about with the legacy mini and MIRV. I had the recipe removed via CT so I forgotten about it. so those recipes have been bonked. I also changed the ENUS to include the (LEGACY) tag
