### ISSUE TITLE
[bug] damageCap setbonus are not respected on mobs

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#360]
I have been seeing this issue for a while when I used a smite V shimmer axe and quadruple digits undead mobs but never had a means to confirm it. That was until something bizarre (and presumably very rare) happened.

![2024-03-11_21 30 46](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/42568033-edb3-4631-928b-6d0605eb0e18)
I came across a skeleton in full DNT armor and managed to survive a hit from it and take it down within 10 hits; Because the armor itself has a high damage cap for a full set; this gave me enough confirmation that the mobs themselves don't have the damage cap applied to them or the Damage cap thing itself is busted (if its supposed to work for all living entities)

![2024-03-11_21 31 14](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/cfd9a545-b26c-44c4-ad34-6e4f5b1594be)

To reproduce: Summon a Skeleton in full DNT armor and with an hp of 1024 and then attack it with a high damage weapon like a shimmer axe with smite V on it.
TIP: to make this easy todo, use ScalingHealth and set your difficulty to high difficulty; HP scaling will be applied on any entity spawn

**Comment by Shibva** [comment]
@Alcatergit on another note; how rare is this bloody thing?

and to reclarify: this mob was likey 750 HP as a result of the setting I have for Scaling health
while I'm fixing some part of my script I could run a test with a fakeplayer to see if its working (thanks only forge version of Carpet)

**Comment by Alcatergit** [comment]
Just tested it and the axe did not kill the mob in DNT armor. It could be that the DNT armor of your mob was out of charge and not active.
Chance for spawn is 1:32768

**Comment by Shibva** [comment]
@Alcatergit that can't be the case! It had to be; unless you also made thst thing super buffed. MF gave me a tap and some leather like boots were evicertrdrd in terms of durability and what was left having chipped more than If not 2/3 of its durability in one hit; plus the amount of HP I have makes this unlikely I would have survived if I haven't. Would it do that if it was not charged 


I'd makes me wonder if you were using the shimmer axe with smite V on it when testing this.

Provide me with a command to spawn this guy and I'll take a look at it; unsure if it could be some fuckery boosting damages
