### ISSUE TITLE
Niche Issue: Atomic Airstrike not oversight with new Mk5 system

### ISSUE THREAD

**Issue by Shibva** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#365]
so I was having some fun and decided to use the atomic air strike desigatnor

next thing I new I saw something off after the blast and on calling in another I see a funny sight; the bomber gets struck down by the nuke. It never did this before but all nukes are now using the mk5 system changes so... It technically shoots itself down after dropping the payload before it could clear the kill radius.

Not sure if this is a bug that should be fixed or made to stay is its a bit hilarious; did someone not tell them that the payload was greater or something? XD

Video: https://cdn.discordapp.com/attachments/936371750126645278/1223019154114613388/20240328-2120-31.9742987.mp4?ex=66185458&is=6605df58&hm=22c7f236a32773cf7ec0d1f1a2690b47426388c16493e5592a7b885040eec7d5&

**Comment by Shibva** [comment]
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/38770780/1a12438b-f020-44f0-b7af-bf1f4be79a14)

**Comment by Shibva** [comment]
also as a nice suggestion, could these things be persistent/chunkloaded? they dont nomarly work if the entity is outside of player render distance; having it forceload when used would be nice (the plane itself I mean; its an issue with all desigantor strikes)

**Comment by Alcatergit** [comment]
When i tested it the nuke did not shoot down the plane in dev. So i guess it is fixed with the next update.
