### ISSUE TITLE
Bug: Fluid ducts do not save their type when set by fluid template

### ISSUE THREAD

**Issue by TNTTVSGOU** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#37]
It seems that whenever the server restarts, some of the fluid identifiers for these pipes go blank, causing the pipes to not connect，just like this (I'm using translation software, which may lead to inaccurate descriptions)
![QQ截图20230103151950](https://user-images.githubusercontent.com/77508516/210385505-3b455de8-5c1a-427b-b135-6c05dad67a7c.png)

**Comment by Alcatergit** [comment]
That is strange - can you replicate that? Does it only happen after the first restart or does it get worse if you restart a few times in a row?

**Comment by TNTTVSGOU** [comment]
It seems that there are two cases of this bug, the first one is that the fluid pipes do not break as shown in the picture, but there is a situation where the fluid cannot be transported; the second case is that the fluid pipes break as shown in the picture and the fluid cannot be transported. The first case seems to occur every time the server is restarted, causing us to spend a lot of effort to find the problem (most of the time we dig out the fluid pipes and put them back in place), the second case is very uncertain and has only occurred twice since the server was created. At the moment it is not known if a few more reboots will make it worse

**Comment by Alcatergit** [comment]
Does it happen only to specific fluid pipe or all pipes? What does WAILA show when looking at the pipes? It could be that the old pipe system is used from an old world. What would happen if you replace pipes with newly placed ones?

**Comment by TNTTVSGOU** [comment]
The second case seems to happen in a separate Chunk (like in the picture), but the problem in the first case seems to happen in every corner, Wawla shows the fluid pipe as fluid_duct_mk2. If I reposition the pipe, it will show the bug again on the next server restart (maybe, I'm not really sure)
![2023-01-06_19 24 53](![2023-01-06_19 25 15](https://user-images.githubusercontent.com/77508516/211015209-eb5bf8c5-8ae1-4bdc-9fa7-eda314533913.png))

**Comment by NONPLAYT** [comment]
same

**Comment by Alcatergit** [comment]
Do the pipes still transfer fluids meaning it is a rendering thing or do they dont transfer any meaning the pipes fluid has be reset?

**Comment by DNIWE041** [comment]
I got this issue too, only in one chunk. Singleplayer, but im open it to LAN. Chunk-loader (chicken chunks) in 5x5 mode cover all my base including this chunk and other chunks with pipes.
Bug can't be fixed by pressing F3+A (chunk reloading).
In my case it's a visual bug, pipes still transfer peroxide to SILEX.

![image](https://user-images.githubusercontent.com/76884831/214045984-702124cb-9ca8-4f2c-ae5c-9a77358dcf3e.png)

**Comment by ntmleafia** [comment]
got the same issue aswell
singleplayer

on bottom of rbmk lol
one notable thing is that i placed different types of ducts next to others

broken 1
![スクリーンショット (2340)](https://user-images.githubusercontent.com/121738096/215963279-11c078eb-6316-4e9c-a35f-054b0b38c874.png)

broken 2
![スクリーンショット (2341)](https://user-images.githubusercontent.com/121738096/215963333-8a20544f-ded2-4059-86aa-2b50760aeb1f.png)

fixed 1
![スクリーンショット (2342)](https://user-images.githubusercontent.com/121738096/215963478-a0c30ea9-d9c6-4be0-bb74-1878d1292e79.png)

fixed 2
![スクリーンショット (2343)](https://user-images.githubusercontent.com/121738096/215963490-1eb0b15d-15da-4e51-b113-5e89c849cf3a.png)

Edit: joining after fixing broke it again
Edit 2: everytime i rejoin it breaks again, likely in the same way
Edit 3: exploding the rbmk made the crash similar to this one https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/issues/10

world download if necessary
https://drive.google.com/file/d/1EgAJwz-z3Dg_eWikvHasKq7rzS1VCTfH/view?usp=share_link
it says many mods are missing but it works with only hbm

**Comment by Alcatergit** [comment]
I have a theory why it happens. Could it be that the fluid template was used to set the fluidtype of these pipes?
Bc i may have found a bug where the change of the fluidtype in the duct does not get saved. It could explain why it happened after restarts.
Ill put the bug fix into the next update. Maybe that fixes it.

**Comment by Alcatergit** [comment]
I think it is fixed now
