### ISSUE TITLE
Glider jetpack not working

### ISSUE THREAD

**Issue by Stupidiot5** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#377]
The glider jet pack doesn’t turn on/off when I try to use it. I let some of my friends try to turn it on while on my server but that didn’t work, and yes It does have fuel in it.

**Comment by corruptedbyte** [comment]
Have you seen keybinds or tutorials on it? Try pressing J

**Comment by Stupidiot5** [comment]
That worked. Thanks
