### ISSUE TITLE
Auto ejecting machines put items in black/white list inventory of conveyor ejector

### ISSUE THREAD

**Issue by WebmasterAnonymail** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#380]
Some machine put automatically items in output (mining laser, cargo landing pad, the excavator (cf #314)), this work perfectly with chest but with conveyor ejector, the items go first in the black/white list inventory, and when we click it they disapear 
This is an exemple of setup :
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/66117859/d2a3f583-5133-4ddd-9cb1-c293fe24ec24)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/66117859/0fbb6f91-9bf0-471e-a0c8-cd070698dfc6)

and the results :
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/66117859/ec33cf1f-41d7-40fb-ae2d-96dc4b78d6b6)
(here there is another problem : the battery is extracted from the miner by the extractor, but this is not the main problem)
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/66117859/188aa27f-0e01-4f15-9b0e-eba9ff6df183)

**Comment by Alcatergit** [comment]
Just put a crate in between them like everyone else.
