### ISSUE TITLE
An issue with the nukes

### ISSUE THREAD

**Issue by artar787** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#386]
Wanted to report a potential problem

When a nuke goes off the area beneath the water level won't get submerged

It used to work so when a nuke went off the areas under the water level would get submerged

**Comment by Alcatergit** [comment]
The nuke will only fill the crater if there is enough water in the area. So when there is high humidity or an ocean where the bomb is detonated. No flooding in deserts/plains/forests and flooding in oceans/beaches/jungles/swamps.
