### ISSUE TITLE
Can't made schrabidium ore by using nuclear explosion & crucible render & sideways blast door didnt work

### ISSUE THREAD

**Issue by DNIWE041** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#4]
**Uranium ore.**
With old nuclear explosion system we can made schrabidium ore if we put uranium ore into nuclear explosion (large, not like fat-man m42 catapult with standart mini-nuke, we need nuclear explosion like we using high yield mini-nuke or nuclear bombs as fat man, little boy, etc).
But with new algorithm it didnt work. Old algorithm turns uranium ore into schrabidium on fallout stage, when earth\ stone \ etc replaced into sellafite and dead grass. And if you put uranium ore on right distance it didnt beed destroyed, and turn into schrabidium ore like stone turns into sellafite.

From wiki `"When exposed to the radiation of a nuclear or dirty bomb, it has a 1/100 chance to turn into [Schrabidium Ore]. If it does not turn, it will become "scorched", which cannot be converted into Schrabidium but can still yield uranium."`

And ore don't scorched after explosion.
Screenshot for example with schrabidium cluster (same algorithm to made euphemium coated cluster, but you ned to use balefire explosion, and if cluster get in fire after explosion you get euphemium). It's working.

![image](https://user-images.githubusercontent.com/76884831/203781320-f419187c-876d-416f-865f-6a01eb84fad4.png)
And second with uranium. 
![image](https://user-images.githubusercontent.com/76884831/203781361-852a9b44-82db-4c78-9603-1aaf6cc4072a.png)
Third with old explosion (using 40mm grenade launcher with `Привет` ammo).
![image](https://user-images.githubusercontent.com/76884831/203782176-f3a3cced-bd00-4df4-b868-2c8c599e3905.png)
And 1.7.10 verison.
![image](https://user-images.githubusercontent.com/76884831/203782849-15803388-f345-4153-b86a-dc042ba47d82.png)
**CRUCIBLE.** Also crucible lost his glowing. Old-new on screen.
![image](https://user-images.githubusercontent.com/76884831/203784018-77d28718-e7d5-408a-a194-ba9274ed6f20.png)

**Sideways blast door** didnt work. Both (window and keypad). No reaction to redstone  \ code lock \ both in the same time (access granted + redstone). Also no reaction to detonator (other doors like silo hatch can be opened by using detonator) with red text in chat `Target incompatible or too far away`.
No screenshot needed.

**Comment by DNIWE041** [comment]
Also old issue with unloaded chunks. But in 'very easy' var. Because not so many loaded chunks. And after a while they almost unloaded.
This problem caused by gas.
For example old issue in Drillgon version (fixed by Golem):
https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/issues/173
![image](https://user-images.githubusercontent.com/76884831/203792046-6d04a3db-f344-45ce-9ba0-10c98efb7905.png)

**Comment by DNIWE041** [comment]
And how i can change a spawn rate for this in my world? Can't find string in config. 
![image](https://user-images.githubusercontent.com/76884831/203792911-e4610add-0c98-4044-89b4-ed9945be385b.png)
I want to do it because they not so rare. 3 pieces in one screen.
![image](https://user-images.githubusercontent.com/76884831/203793235-5d926ddc-dc6e-4a96-aa9c-94b8495f1af9.png)

**Comment by Alcatergit** [comment]
The chance of schrabidium conversion now depends on distance. Closer -> Better. Also you can to it with dropping radioactive powders instead of explosions.
The Crucible Glow never existed in 1.12.2
Working on making sellafite spawns configurable

**Comment by DNIWE041** [comment]
`The chance of schrabidium conversion now depends on distance. Closer -> Better.`
Ok. Are the new chances higher or lower? And maybe i did something wrong. Because i get zero schrabidium ore when im trying to explode  ~500 blocks of uranium ore. I'll try powders.
Also ore don't scorched after explosion. So, i can use all ore again and again?
Edit: its working with powders.

`The Crucible Glow never existed in 1.12.2`
But it's existed (it's cant light up blocks around you) . + and something like hot air effect. On screenshot, its 1.12.2 version on the left side, 1.6.5a or something.

**Comment by Alcatergit** [comment]
> But it's existed (it's cant light up blocks around you) . + and something like hot air effect. On screenshot, its 1.12.2 version on the left side, 1.6.5a or something.

That is strange since i did not change anything about the crucible

**Comment by Alcatergit** [comment]
Radial Fallout converts uranium ore within 10% of the total radius.
Rain Fallout converts uranium ore within 5% of the total radius.
