### ISSUE TITLE
[Suggestion] Infinity Oil Deposits config option

### ISSUE THREAD

**Issue by MiniRaptor** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#401]
I'm tired of moving all the installations and buildings everything again, just to extract oil. Please add ability to make oil deposits infinity

**Comment by 3114396pig** [comment]
There's something called **Bedrock Oil Deposit** which generates in bedrock layer.
![526874](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/4a42c775-f176-4866-8a83-487641f13498)

**Oily sand**, **Oily dirt** and its variants **Dead dirt** and **Red oily sand** will appear around the surface where **Bedrock Oil Deposit** is generated.
<img width="569" alt="Screen shot 1" src="https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/333c9977-b704-4d0a-934d-ce842ccab807">

You can use **Hydraulic Fracking Tower** to get **infinite** oil and natural gas by providing **Fracking Solution**.
<img width="698" alt="Screenshot 2" src="https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/9adc736b-eb53-465a-871b-183a3b0c9769">

<img width="1280" alt="Screenshot 3" src="https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/88887515/c09ab310-2c49-4dbf-aebd-2401590d149d">

**Comment by Stupidiot5** [comment]
Play the mod a little before you post something like this

**Comment by MiniRaptor** [comment]
> There's something called **Bedrock Oil Deposit** which generates in bedrock layer. ![526874](https://private-user-images.githubusercontent.com/88887515/333847674-4a42c775-f176-4866-8a83-487641f13498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzIxNTUsIm5iZiI6MTcxNjczMTg1NSwicGF0aCI6Ii84ODg4NzUxNS8zMzM4NDc2NzQtNGE0MmM3NzUtZjE3Ni00ODY2LThhODMtNDg3NjQxZjEzNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MDEzNGZlMTY3MjljMThlMzRkZjAwOGIzZDUwMGRlYjg1ZjZjMGJjZjI0YjJhNDUyNDQzNTQ2MDcwNmNkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vrlfb-9dW7Hxyi8aLTtesVP9mhDvThYmPreRkfHBB6o)
> 
> **Oily sand**, **Oily dirt** and its variants **Dead dirt** and **Red oily sand** will appear around the surface where **Bedrock Oil Deposit** is generated. <img alt="Screen shot 1" width="569" src="https://private-user-images.githubusercontent.com/88887515/333847698-333c9977-b704-4d0a-934d-ce842ccab807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzIxNTUsIm5iZiI6MTcxNjczMTg1NSwicGF0aCI6Ii84ODg4NzUxNS8zMzM4NDc2OTgtMzMzYzk5NzctYjcwNC00ZDBhLTkzNGQtY2U4NDJjY2FiODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYTAyZjk4NjY5MDBhOWJiMTc5OTFiZjU1Nzc0MGQ5MjkwZmU5OWM0MDAyZmY0NjkwMDFmYjc4Y2I0OTdhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.03MfD75-hNrdjgd9FMNBDhY1wCRHL-d2GqQ78IIkjE8">
> 
> You can use **Hydraulic Fracking Tower** to get **infinite** oil and natural gas by providing **Fracking Solution**. <img alt="Screenshot 2" width="698" src="https://private-user-images.githubusercontent.com/88887515/333847716-9adc736b-eb53-465a-871b-183a3b0c9769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzIxNTUsIm5iZiI6MTcxNjczMTg1NSwicGF0aCI6Ii84ODg4NzUxNS8zMzM4NDc3MTYtOWFkYzczNmItZWI1My00NjVhLTg3MWItMTgzYTNiMGM5NzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYjQ3OGU2NmRkNDE1ZjQ3ZjM0OTMxNTUwOTQ4MTZmMjMxMjY2NjZhNGU4MTMwZmQzYTE3MTMwYWUwZTNhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UsLX3gzhw1JqMO2XYYq999ssGgGuermJWNlNrnCVrJI">
> 
> <img alt="Screenshot 3" width="1280" src="https://private-user-images.githubusercontent.com/88887515/333847794-c09ab310-2c49-4dbf-aebd-2401590d149d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzIxNTUsIm5iZiI6MTcxNjczMTg1NSwicGF0aCI6Ii84ODg4NzUxNS8zMzM4NDc3OTQtYzA5YWIzMTAtMmM0OS00ZGJmLWFlYmQtMjQwMTU5MGQxNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxY2IzMTY4MjFjOTdkNzU0NTg5ZWNiYjMyNjI1YTMxNTA1Y2FlN2U2ZDNkZjdlYzcxYjc1ZmEyZjMwOWRmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZ-TmGQzNUjgvw4XVswSQOnUiMokSO8zZfTFIuSmchA">

Ooof, i watched a lot of guides but no one told bout this feature there. Thank you
