### ISSUE TITLE
hbm gun conflict with immersive combat

### ISSUE THREAD

**Issue by Gerald4567** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#407]
the guns in this mod have a compatibility issue with immersive combat preventing some weapons from firing and for the most part locking into a swing animation 

I did look into this more and there is a way I could blacklist all guns as a whole but it requires me to have access to the source code which is why I'm exactly here I'm not asking for the code but really for more help to solve this issue to have these 2 mods work together better

![Capture](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/138883898/919c1e73-9678-4296-b9fc-fc08b62a07e1)

https://youtu.be/q5_5MYDin6k

**Comment by DNIWE041** [comment]
...
HBM is open-source mod. You can click `<> Code` in left top corner and get it.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/76884831/7c304629-98d9-4887-97f3-9f9bac5abe1a)

You can investigate code here or download (click green button on right side  `<> Code`  and select `Download ZIP` ) and edit \ investigate it on your computer.
But btw if you need add path in this config to gun .class file, you just need to open HBM .jar file with any ZIP archiver (like WinRAR) and investigate it.

**Comment by Gerald4567** [comment]
Ok thanks I'll be sure to do this

**Comment by MangoPigeon** [comment]
Gerald,  any progress on the blacklisting ?

**Comment by Gerald4567** [comment]
Right now no because I'm at work I'll do so once I'm able to

**Comment by Gerald4567** [comment]
ok i managed to unzip the file and got close to pin pointing the stuff i need but im still a bit stuck as far as i can tell it looks like i would need to try a number of options ill post what i found in case someone can give something more than just trial and error
![Capture](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/138883898/4b8b397e-d997-42e1-897a-c814266cd114)
![image_2024-06-02_094731865](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/138883898/25892503-d20c-44c5-af04-ca3207ec3364)

**Comment by Gerald4567** [comment]
![image_2024-06-02_094910307](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/138883898/468a4ed0-3125-40f5-a9a8-7f7bd7a23f75)
sorry the others were pretty bad here is a better one

**Comment by Gerald4567** [comment]
ok i got help and theres a way to get it to work for a lot of the guns as there might be some outliers but this helps a lot 
![Screenshot_20240602_130101_Discord](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/138883898/d4497939-0340-4816-83cf-27aa13663419)
