### ISSUE TITLE
Is there some way to force fluids through fluid ducts?

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#41]
![Screenshot 2023-01-12 193137](https://user-images.githubusercontent.com/60857805/212216544-75d495af-85a3-4d3c-8548-6c24244a5fc3.png)
I've been trying various ways to force water into this duct but it doesn't seem to be working, I've tried connecting them to thermal dynamics fluiducts, and tried connecting them to mekanism pipes, but neither of those will directly connect, and they don't seem to be drawing from mekanism tanks. Is there some kind of pump block, or something like that, which will force fluids through the ducts.

**Comment by xenoulexi** [comment]
Also, on that note is there some way that, with the normal multiblock reactor, we can add more than just 4 access hatches/fuel hatches to the reactor, I can place one on each side horizontal of the core but place them higher or lower on the reactor, or next to one-another horizontally, they say they can't detect the reactor core block.

**Comment by ntmleafia** [comment]
extraction mode works so use screwdrivers

**Comment by xenoulexi** [comment]
Thanks for that
