### ISSUE TITLE
BUG WITH ORE ACIDIZER

### ISSUE THREAD

**Issue by NightmareLeyend** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#415]
![Screenshot (6)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/174069604/a77574d6-7b0d-4f78-a718-edb0365f3b8b)
![Screenshot (7)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/174069604/002be7c0-8e2a-40ee-81af-44d2dc2dacfa)
![Screenshot (8)](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/174069604/6a02782e-c74f-40a4-aae6-739917a63465)
(sorry for my english) I finally obtained the Ore Acidizer and I wanted to make some Redstone Crystals. The recepy requieres Hydrogen peroxide and Redstone ore, but when I tried to fill the Ore Acidizer with Hydrogen Peroxide, It doesn't get fill with it. If you use another liquid like Sulfuric acid, it works perfectly. So any recepy that requieres Hydrogen Peroxide (a lot of recepies do) can't be done/use (idk how to say it). Also, when you fill the Ore Acidizer with something like Sulfuric Acid, you have to use it all to empty the Ore Acidizer. Some screenshots so you see what i'm talking about.

**Comment by DNIWE041** [comment]
??? Everything ok with peroxide. Maybe it's problem with your modpack, some incapability? Maybe other your mods adds some peroxide? Check acidizer without mods.
Im using NTM 2.0.2 here.
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/76884831/f759891b-dc3f-4020-af10-50c509efff9a)

**Comment by NightmareLeyend** [comment]
> ??? Everything ok with peroxide. Maybe it's problem with your modpack, some incapability? Maybe other your mods adds some peroxide? Check acidizer without mods. Im using NTM 2.0.2

Thank you, I checked every mod that I had and the problem was Lycinated mobs, i don't know why but it was Lycinated mobs Mod.
