### ISSUE TITLE
Issu with build form the GIT

### ISSUE THREAD

**Issue by juciom** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#419]
some web site for dependancy dosent exist

**Comment by Shirhix** [comment]
I've got the same problem. But just not some, all websites don't seem to exist. How is this possible?
`* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve mezz.jei:jei_1.12.2:4.16.1.302_mapped_snapshot_20171003-1.12.
  Required by:
      project :
   > Could not resolve mezz.jei:jei_1.12.2:4.16.1.302_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.galacticraft.net/repository/legacy/mezz/jei/jei_1.12.2/4.16.1.302_mapped_snapshot_20171003-1.12/jei_1.12.2-4.16.1.302_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.galacticraft.net/repository/legacy/mezz/jei/jei_1.12.2/4.16.1.302_mapped_snapshot_20171003-1.12/jei_1.12.2-4.16.1.302_mapped_snapshot_20171003-1.12.pom'.
            > Connect to maven.galacticraft.net:443 [maven.galacticraft.net/93.186.202.4] failed: Connection refused: connect
   > Could not resolve mezz.jei:jei_1.12.2:4.16.1.302_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.mcmoddev.com/mezz/jei/jei_1.12.2/4.16.1.302_mapped_snapshot_20171003-1.12/jei_1.12.2-4.16.1.302_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.mcmoddev.com/mezz/jei/jei_1.12.2/4.16.1.302_mapped_snapshot_20171003-1.12/jei_1.12.2-4.16.1.302_mapped_snapshot_20171003-1.12.pom'.
            > maven.mcmoddev.com
> Could not resolve dev.galacticraft:galacticraft-legacy:4.0.2.283_mapped_snapshot_20171003-1.12.
  Required by:
      project :
   > Could not resolve dev.galacticraft:galacticraft-legacy:4.0.2.283_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.galacticraft.net/repository/legacy/dev/galacticraft/galacticraft-legacy/4.0.2.283_mapped_snapshot_20171003-1.12/galacticraft-legacy-4.0.2.283_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.galacticraft.net/repository/legacy/dev/galacticraft/galacticraft-legacy/4.0.2.283_mapped_snapshot_20171003-1.12/galacticraft-legacy-4.0.2.283_mapped_snapshot_20171003-1.12.pom'.
            > Connect to maven.galacticraft.net:443 [maven.galacticraft.net/93.186.202.4] failed: Connection refused: connect
   > Could not resolve dev.galacticraft:galacticraft-legacy:4.0.2.283_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.mcmoddev.com/dev/galacticraft/galacticraft-legacy/4.0.2.283_mapped_snapshot_20171003-1.12/galacticraft-legacy-4.0.2.283_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.mcmoddev.com/dev/galacticraft/galacticraft-legacy/4.0.2.283_mapped_snapshot_20171003-1.12/galacticraft-legacy-4.0.2.283_mapped_snapshot_20171003-1.12.pom'.
            > maven.mcmoddev.com
> Could not resolve com.azanor:Baubles:1.12-1.5.2_mapped_snapshot_20171003-1.12.
  Required by:
      project :
   > Could not resolve com.azanor:Baubles:1.12-1.5.2_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.galacticraft.net/repository/legacy/com/azanor/Baubles/1.12-1.5.2_mapped_snapshot_20171003-1.12/Baubles-1.12-1.5.2_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.galacticraft.net/repository/legacy/com/azanor/Baubles/1.12-1.5.2_mapped_snapshot_20171003-1.12/Baubles-1.12-1.5.2_mapped_snapshot_20171003-1.12.pom'.
            > Connect to maven.galacticraft.net:443 [maven.galacticraft.net/93.186.202.4] failed: Connection refused: connect
   > Could not resolve com.azanor:Baubles:1.12-1.5.2_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.mcmoddev.com/com/azanor/Baubles/1.12-1.5.2_mapped_snapshot_20171003-1.12/Baubles-1.12-1.5.2_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.mcmoddev.com/com/azanor/Baubles/1.12-1.5.2_mapped_snapshot_20171003-1.12/Baubles-1.12-1.5.2_mapped_snapshot_20171003-1.12.pom'.
            > maven.mcmoddev.com
> Could not resolve cofh:RedstoneFlux:1.12-2.1.0.6_mapped_snapshot_20171003-1.12.
  Required by:
      project :
   > Could not resolve cofh:RedstoneFlux:1.12-2.1.0.6_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.galacticraft.net/repository/legacy/cofh/RedstoneFlux/1.12-2.1.0.6_mapped_snapshot_20171003-1.12/RedstoneFlux-1.12-2.1.0.6_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.galacticraft.net/repository/legacy/cofh/RedstoneFlux/1.12-2.1.0.6_mapped_snapshot_20171003-1.12/RedstoneFlux-1.12-2.1.0.6_mapped_snapshot_20171003-1.12.pom'.
            > Connect to maven.galacticraft.net:443 [maven.galacticraft.net/93.186.202.4] failed: Connection refused: connect
   > Could not resolve cofh:RedstoneFlux:1.12-2.1.0.6_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.mcmoddev.com/cofh/RedstoneFlux/1.12-2.1.0.6_mapped_snapshot_20171003-1.12/RedstoneFlux-1.12-2.1.0.6_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.mcmoddev.com/cofh/RedstoneFlux/1.12-2.1.0.6_mapped_snapshot_20171003-1.12/RedstoneFlux-1.12-2.1.0.6_mapped_snapshot_20171003-1.12.pom'.
            > Dies ist normalerweise ein zeitweiliger Fehler bei der Aufl├Âsung von Hostnamen. Grund ist, dass der lokale Server keine R├╝ckmeldung vom autorisierenden Server erhalten hat (maven.mcmoddev.com)
> Could not resolve net.minecraftforge:forge:1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.
  Required by:
      project :
   > Could not resolve net.minecraftforge:forge:1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.galacticraft.net/repository/legacy/net/minecraftforge/forge/1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12/forge-1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.galacticraft.net/repository/legacy/net/minecraftforge/forge/1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12/forge-1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.pom'.
            > Connect to maven.galacticraft.net:443 [maven.galacticraft.net/93.186.202.4] failed: Connection refused: connect
   > Could not resolve net.minecraftforge:forge:1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.
      > Could not get resource 'https://maven.mcmoddev.com/net/minecraftforge/forge/1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12/forge-1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.pom'.
         > Could not GET 'https://maven.mcmoddev.com/net/minecraftforge/forge/1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12/forge-1.12.2-14.23.5.2860_mapped_snapshot_20171003-1.12.pom'.
            > maven.mcmoddev.com`
