### ISSUE TITLE
Unable to open stoneblock 2 with hbm's ntm.

### ISSUE THREAD

**Issue by BellTheDawg** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#422]
When I try to open stoneblock 2 with the mod installed, this shows up.  No idea why, and I cant get the crash logs, But I CAN get the Minecraft logs due to using multimc to open it.
Compatibility would be appreciated, but I know that it might be hard, so its ok if you don't. 

https://paste.ee/p/ZU6zT

![3333331](https://github.com/user-attachments/assets/73e2c108-157c-4c2e-b98a-ab1b3bb44b82)

(I tried clicking, it didn't work)

**Comment by TheSlize** [comment]
Switch to the **2.0.2** version of NTM and install **Not Enough IDs** - should help you with this particular crash

**Comment by BellTheDawg** [comment]
Testing it right now

**Comment by BellTheDawg** [comment]
Thanks, appreciate it!
