### ISSUE TITLE
Bug: Radiation not contained by structures

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#43]
blocks like concrete bricks doesn't really stop radiation from leaking
seems like your "pocket rebuilding" part has a problem, as this only happens after placing radiation-resistant blocks

enclosed room with waste block in it
![image](https://user-images.githubusercontent.com/121738096/212466045-a9976b5e-a919-4e15-b6b3-1b5b59ca2b74.png)

after placing concrete bricks in that chunk
![image](https://user-images.githubusercontent.com/121738096/212466059-63ed370c-8c21-49db-9188-a82a7bc90ef3.png)

radiation level lowering if i don't place any
![image](https://user-images.githubusercontent.com/121738096/212466143-b827a5aa-7554-44aa-a15f-b76b39ca6866.png)

**Comment by KaxelOleg** [comment]
As I understand it, the radiation leak from the barrel goes despite the concrete bricks? I also wanted to know if the leak occurs after you put the room out of concrete or before?

**Comment by ntmleafia** [comment]
since a video would say thousands of words i'll put it here
the radiation is compeltely sealed, and placing radiation-resistant block leaks it
if you're wondering, this doesn't happen with non-radiation-resistant blocks
https://user-images.githubusercontent.com/121738096/212484447-17f23c8e-c21d-4e22-982b-56a069521949.mp4

edit: the blastdoor is open, but don't care about it, as the game seems to not take that into account

**Comment by KaxelOleg** [comment]
> since a video would say thousands of words i'll put it here the radiation is compeltely sealed, and placing radiation-resistant block leaks it if you're wondering, this doesn't happen with non-radiation-resistant blocks https://user-images.githubusercontent.com/121738096/212484447-17f23c8e-c21d-4e22-982b-56a069521949.mp4
> 
> edit: the blastdoor is open, but don't care about it, as the game seems to not take that into account

I think I know how to fix it, but I need more time to fix it without breaking anything, the problem is with the radiation system itself.

**Comment by KaxelOleg** [comment]
> since a video would say thousands of words i'll put it here the radiation is compeltely sealed, and placing radiation-resistant block leaks it if you're wondering, this doesn't happen with non-radiation-resistant blocks https://user-images.githubusercontent.com/121738096/212484447-17f23c8e-c21d-4e22-982b-56a069521949.mp4
> 
> edit: the blastdoor is open, but don't care about it, as the game seems to not take that into account

I think I fixed it, but maybe because of my fix, the speed when you make space open to radiation begins to spread slowly
https://kapwi.ng/w/JDI6ol9kCD
The solution (possible), as it turned out, was much simpler than I thought. It was just necessary to synchronize the reboot of the chunks after placing the protective block along with the radiation itself. As for the doors, it is not difficult to implement so that radiation, if available, can penetrate the door if it is open

**Comment by Alcatergit** [comment]
> It was just necessary to synchronize the reboot of the chunks after placing the protective block along with the radiation itself.

How did you manage that?
