### ISSUE TITLE
(QoL) Please add [neutrino lens](https://nucleartech.wiki/wiki/Neutrino_Lens)

### ISSUE THREAD

**Issue by Abuir** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#438]
Without them satellite with depth-resource scanning module is way more useless

**Comment by TheSlize** [comment]
**Already did in 2.0.3 in-dev. Please have patience for the incoming update**

**Comment by Abuir** [comment]
> **Already did in 2.0.3 in-dev. Please have patience for the incoming update**

ok thanks
