### ISSUE TITLE
RBMK Moderated Fuel Rod don't work properly

### ISSUE THREAD

**Issue by DNIWE041** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#46]
It works like default Fuel rod, does not turn Fast neutrons into Slow with one exception it slow down neutrons who coming from other fuel rods into our moderated rod (and it still works not well), not from tungsten carbide reflectors, does not slow down neutrons for irradiation channel and etc. 

BUT in 1.7.10 all fine, thats why i think it's a bug in 1.12.2. In 1.7.10 Moderated Fuel Rod works like a moderated, it slows all neutrons - passed thru, outcomes from fuel inside it and etc. It's works like a graphite moderator+fuel rod (This moderated fuel rod can be made from graphite blocks and fuel rod + bismuth, so..).

**For example i cant made ultra-small self - sustaining reactor with 4 neutron reflectors and one moderated fuel rod.
2 screenshots with ultra small reactor. Attention to FluxSlow stats. It's zero in 1.12.2.
1.7.10 mod**
![image](https://user-images.githubusercontent.com/76884831/213933533-013a912a-00c1-4e0b-829b-790b536b4383.png)

**1.12.2 mod** 
![image](https://user-images.githubusercontent.com/76884831/213933541-0f200f50-87e6-48a9-89a1-06360e909d78.png)

For info - Moderated Fuel Rod it's a combined Fuel rod with Graphite moderator (2 in 1), so it will slow down all neutrons: passed thru, comes out from fuel inside and etc. Moderated Fuel Rod is a next-tier fuel rod. It gives opportunity to create a more compact reactor.

**Comment by Alcatergit** [comment]
Found and fixed the bug. Thanks for the info. It will be in the next update.
