### ISSUE TITLE
radiation lasts forever?

### ISSUE THREAD

**Issue by ntmleafia** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#48]
sellafites produce radiation, nukes creates sellafites.
i think that makes radiation go worse and worse over time, just wondering if it is actually supposed to be like this

![image](https://user-images.githubusercontent.com/121738096/214615342-d8f26a27-3fa7-4d88-ba00-a5a230a13a1d.png)
A **little** nuke resulting in an enormous contamination

**Comment by Alcatergit** [comment]
Ye block radiation works like this: They have a radiation value that is added each second to the chunks radiation until the maximum chunk radiation is reached. So Sellatife corium has rad values of (40, 4000) so it will pump out radiation into the chunk with 40 s until the chunk radiation reaches 4000.

**Comment by Alcatergit** [comment]
So the main goal would be to remove the sellafite to decontaminate it. One way is to do so is to use the solinium bomb.

**Comment by ntmleafia** [comment]
Oh i forgot solinium bomb exists. thank you btw
