### ISSUE TITLE
Suggestion for new kinds of enviromental hazards (and other stuff)

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#49]
My ideas include a form of the asbestos particles/coal dust/chlorine gas blocks that persist prominently, instead of fading over time... The idea is that these will form in bubbles underground and present a hazard while mining. It would also be neat to have sellafite veins that form underground and present a radiation hazard while mining, similar to radiation hotspots in the desert (alternatively, for the underground radiation hazard instead of sellafite, there could spawn underground structures that are supposed to be ancient geological waste repositories, with ancient scrap metal and blocks of corium), one more neat environmental hazard would be a naturally occurring volcano core block that spawns rarely at bedrock level and will randomly become active and form volcanos before going dormant for a period of time.
Also, as a bit of a side suggestion, it would be cool to have pink-cloud blocks similar to the chlorine blocks, alongside a pink-cloud seal like the chlorine seal. Perhaps also some "pink-stained bricks" and "dead pink trees" or something along those lines, so the pink cloud can taint other nearby blocks as it does with the FM radio... Perhaps these pink-stained blocks slow down and cause damage to entities that walk on them.
Also, it would be cool if balefire explosions form a green-colored variant of sellafite, a kind of "balelite", which is less radioactive but causes nausea when stepped on.
Also a pebble-bed or pressurized water reactor, to act as a lower-power but safer alternative to the RBMK.

**Comment by xenoulexi** [comment]
Some other random ideas include: Multiblock breeder reactors, liquid taint, and to make fallout blocks be thinner like snow or carpet.

**Comment by xenoulexi** [comment]
Also, you could make antenna blocks have a practical use by making them a form of wireless redstone transmission. And perhaps you can implement a much larger and more powerful multiblock version of the corrupted broadcaster which can be turned on and off for base defense (along with a way to defend the player from the effects of the broadcaster) (admittedly the reason why I suggest this is because I kinda want to make a version of the STALKER Brain Sorcher on my server)

**Comment by Alcatergit** [comment]
> make fallout blocks be thinner like snow or carpet. 
Done
