### ISSUE TITLE
None of the big doors opens.

### ISSUE THREAD

**Issue by LeKripiY** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#5]
From the sideway sliding doors to the huge bunker latch, water door and else, none of them work, you just can't open them.

**Comment by DNIWE041** [comment]
use detonator or redstone signal
sideway doors (both) bugged and didnt work

**Comment by Alcatergit** [comment]
They work now like iron doors. So you can press a button and nobody can get in.
