### ISSUE TITLE
[No Config to disable Depth Ore Veins in hbm_dimensions.cfg]

### ISSUE THREAD

**Issue by whatsapp2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#50]
Been trying to find an option to disable these ores in specific dimensions but there's no option for it in the dimensions config file.

**Comment by Alcatergit** [comment]
The way to do that is to just remove the dimension entry from the list.
So if you want to remove niter spawning in the overworld f.ex. you would to it like this.

S:01.07_niterSpawnrate <
        0:6
        >

becomes this:

S:01.07_niterSpawnrate <
        >
