### ISSUE TITLE
[Gas pockets don't spawn in world and can't be tweaked]

### ISSUE THREAD

**Issue by whatsapp2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#51]
I've tweaked the dimensions config to try and increase the explosive gas pockets around some dimensions, but I've noticed 2 things, number 1: Both explosive and flammable gas pockets seem to not be spawning in the overworld, nor in any other place, even if the amount per nTH chunk is lowered; number 2: you can't actually tweak the amount of gas/size of the gas pocket in the hbm_dimensions config file

**Comment by Alcatergit** [comment]
That is fixed in version 1.9.4
