### ISSUE TITLE
Bug: RBMK steam channels not accepting water

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#58]
For some reason, sometimes RBMK steam channels just won't accept feedwater... I connect them up with fluid ducts, I have a water source pumping out water, but occasionally the steam channels don't fill. I can fix this by reloading the map, but I'd rather not have to do that.

**Comment by Alcatergit** [comment]
Does that still happen? Ill assume its fixed already.
