### ISSUE TITLE
The modid was repeated with the modid of HarderBranchMining-1.12.2-2.0.0.16

### ISSUE THREAD

**Issue by HJXArthurAtlas** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#62]
The modid was repeated with the modid of HarderBranchMining-1.12.2-2.0.0.16
both are 'hbm'

**Comment by Alcatergit** [comment]
Looks like that makes them not work together. Since i wont change the hbm prefix bc that would bring a ton of problems you could ask the mod author of that mod of he wants to change it. I doubt that tho
