### ISSUE TITLE
For some reason tennessine gets deleted from the cyclotron if you don't speffically run it in the middle orange slot.

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#67]
![Screenshot 2023-02-27 153755](https://user-images.githubusercontent.com/60857805/221693037-2eab9e6e-c72a-419a-a913-d93c62e840e5.png)
I've not tested every recipe, but I'm fairly certain this problem only applies to Tennessine. For some reason, it simply ceases to exist if it appears in any slot other than the middle one.

**Comment by Alcatergit** [comment]
![image](https://user-images.githubusercontent.com/117086491/222708637-fb34c67f-0618-4ac5-a62b-0b0cd5cccf4d.png)
Well it worked fine when i tested it
