### ISSUE TITLE
Proper inputs for machines

### ISSUE THREAD

**Issue by Spookysaw** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#68]
Machines, specifically tested the electric and arc furnace, do not have proper input ports. If you insert something into them through like a hopper or an itemduct from another mod, they fill up the first slot, then the second, and so on. Regardless of where you're inputting from. Not only that it fills up the output slot as well. So if you fill up a furnace with porkchops through a hopper, and remove the cook porked chops from the output slot, the output slot fills up with raw porkchops, breaking it.

**Comment by Alcatergit** [comment]
Thx for the heads up. I just fixed that. It will be in the next Update
