### ISSUE TITLE
Input and Output hatch for Particle accelerator

### ISSUE THREAD

**Issue by OlegKovach** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#7]
Hello, is it possible to add hatches for the particle accelerator in future updates. Yes, there is an access hatch, but if you put more than one, then others do not accept and do not give away items. It would be great for the possibility of automation if there were access hatches to items.  Also, is it currently possible to change crafts using crafttweaker or Groovy Script?Sorry if I posted it in the wrong section

**Comment by Alcatergit** [comment]
You can put more than one access hatch in a accelerator if you place them in the coil that has the accelerator core.
