### ISSUE TITLE
Reinforced Ducrete is misspelled

### ISSUE THREAD

**Issue by Spookysaw** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#70]
Every other form of ducrete is spelled ducrete. Ducrete bricks, smooth ducrete, ect. The reinforced ducrete stairs and slabs are spelled correctly. However, reinforced ducrete itself is spelled 'reinforced durcete'.

**Comment by Alcatergit** [comment]
Fixed that - it will be in the next update
