### ISSUE TITLE
For some reason crates disappear when mined and lose their inventory if you rotate them with a Thermal series cresecent hammer...

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#73]
I lost a crate full of iron when I mined it and it didn't drop anything, not even the crate, it just disappeared... I also lost a ton of items when, with a thermal foundation crescent hammer, I right-clicked on a crate and rotated it, causing the inventory to vanish.

**Comment by Alcatergit** [comment]
> It didn't drop anything
Fixed that
