### ISSUE TITLE
Controling old turrets and replacing to new ones cause crash

### ISSUE THREAD

**Issue by IqwqI1604** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#75]
### The bug is easy to repeat.

Version of the mod: 1.9.0

All you need to do is:

> 1. place old turret
> 2. conect it to a turret controller
> 3. break old turret and plaсe new (orange one) on the same spot
> 4. try to control it 

Result: it works (sort of) but in a few seconds game just crashes.

**Here's a debug log if I'm correct:**
[debug.log](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/10933261/debug.log)

> the start of the world 
> line - 1191
> 
> start of bug repeat  
> line - 19605
> 
> link of old turret
> line - 19613
> 
> And it stops 
> line - 19614

This bug is also in the original hbm 1.7.10
I wouldn't write  bug-report if the old turrets didn't have a craft, but it have a craft and those who run a server with hbm may have problems with this bug.

**Comment by Alcatergit** [comment]
ye just dont do that

**Comment by IqwqI1604** [comment]
Small update on the bug:
[1.9.5 II]
 - the crash only client side. (player ticking issue)
 - works much longer in new versions (5 sec vs 1 min)

The bug is minor no need to fix it. Better fix the generation issue.

**Comment by Alcatergit** [comment]
Fixed
