### ISSUE TITLE
Crash report in mod pack(Berries_And mobs_mod)

### ISSUE THREAD

**Issue by RJHG56** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#8]
Description:
I entered Minecraft and crashed. vanilla fix say was  Berries_And_mobs_mod fault 
I am going to send the crash report to berries and mobs mod  too
here is the crash report 
[crash-2022-11-25_19.20.24-client.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/10095452/crash-2022-11-25_19.20.24-client.txt)

**Comment by Alcatergit** [comment]
The crash says that all item ids are used up (4096). This has nothing to do with this mod. You can try the following:
Delete config and restart (Backup config first)
Install a mod that extends the id limit ([NotEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/notenoughids))
