### ISSUE TITLE
Cooling tower does not place

### ISSUE THREAD

**Issue by Jmanfloppy** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#82]
I added this mod to a pack i've been building for fun and found that the cooling tower doesn't place (see imgur link for screen recording ) https://imgur.com/a/xd1c1vH. 
I'm not sure if it is an issue with mod itself or a compatibility issue the other mods im using. Here is a link to a zip file of the all mods im using, https://drive.google.com/file/d/12G4NYdjpb9URumHA9RQFR9zv7h_BTm9E/view?usp=sharing                                          Java MC version 1.12.2, Forge 14.23.5.2859

**Comment by Alcatergit** [comment]
Nothing is broken here it just has not enough space.
The Fern on the right is blocking it. 
It is a BIG boy with a ground area of 9x9.
You can place it in the air to see its dimensions.
