### ISSUE TITLE
the new merged performance changes lessen max stack size in assembly machines and chemical plants

### ISSUE THREAD

**Issue by Demantier** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#84]
merged commit log is [here](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/commit/0e4a93016940d9947890416dae61cfd29b5f0b36)

on assembly machine, this line of code makes stacked items capped to 18
```
inventory = new ItemStackHandler(18){
			@Override
			protected void onContentsChanged(int slot){
				markDirty();
				OnContentsChanged(slot);
				super.onContentsChanged(slot);
			}

			@Override
			public int getSlotLimit(int slot) {
				return 18;
			}
		};
```
for assembly machines, this makes recipes like cyclotron unusable due to lack of space for other materials.
chemical plant also has this issue but with 21 max stack size
```
inventory = new ItemStackHandler(21) {
			@Override
			protected void onContentsChanged(int slot) {
				markDirty();
				OnContentsChanged(slot);
				super.onContentsChanged(slot);
			}

			@Override
			public int getSlotLimit(int slot) {
				return 21;
			}
		};
```

a workaround is changing 18/21 to 64 or deleting the override

**Comment by Alcatergit** [comment]
Thx for the heads up. I have fixed it. It will be in the next update.
