### ISSUE TITLE
SpeedForce (SpeedsterHeroes) and HBMEE have a weird compatibility crash

### ISSUE THREAD

**Issue by AtomizerEmerald** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#85]
For some reason when activated Speedforce from SpeedsterHeroes, while having HBMEE installed, it crashes the game, from what I could tell from the crash report, its the Speedforce animations/effects causing it, and since the creator has abandoned the project, I can only hope that your able to fix it

[crash-2023-03-29_22.56.24-client.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11107639/crash-2023-03-29_22.56.24-client.txt)

**Comment by Alcatergit** [comment]
I think i found the bug. Check if it works in the next update

**Comment by AtomizerEmerald** [comment]
Okay, thanks!
