### ISSUE TITLE
Depth iron ore turns into gold in the crystallizer

### ISSUE THREAD

**Issue by jet-rain** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#87]
What 
![2023-03-31_15 24 09](https://user-images.githubusercontent.com/84875156/229234630-13b5eb9a-4892-468d-839c-c32de32ecf94.png)
![2023-03-31_15 24 16](https://user-images.githubusercontent.com/84875156/229234652-b357dd34-584d-4885-a035-6c263e444baa.png)

**Comment by Alcatergit** [comment]
Good Find. Just fixed it. It will come in the next update
