### ISSUE TITLE
Hazmat/Liquidator suits not providing *any* gas or airborne particle protection

### ISSUE THREAD

**Issue by Delta9and3** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#88]
None of the hazmat suits are providing protection via their integrated respirators, particularly egregious in the case of the liquidator suit given the recipe. This includes coal and asbestos dust too, meaning one has to forgo the helmet go get protection despite the integrated masks. Even adding the armor modification masks does not help. Additionally, compared to the 1.7 version of HBM the airborne threats system in general is *vastly* simplified, please consider bringing it up to parity.

**Comment by Alcatergit** [comment]
Hazmat suits will get coal and asbestos protection in the next update.
