### ISSUE TITLE
Incorrrect Pumpjack animations

### ISSUE THREAD

**Issue by jet-rain** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#89]
The pumpjack behaves the same way as the derrick but it should have its own moving animation
![2023-04-02_14 54 27](https://user-images.githubusercontent.com/84875156/229378667-4ec0a2aa-70ca-4743-85b8-bfc2ae8a1c2b.png)

**Comment by Alcatergit** [comment]
Damn good find. Just fixed it. Will be in the next update.
