### ISSUE TITLE
DFC is not working

### ISSUE THREAD

**Issue by ArkhamHedler** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#90]
The Dark Fusion Core reactor is not working, it won't turn on.
Edit: In fact the dfc it is working yes, but the lithium catalyst is not working, at least the texture does not appear.

**Comment by Alcatergit** [comment]
It is working but needs a clever setup. Looping DFC setups are the meta. https://www.youtube.com/watch?v=0qRJOUAuMWY&t=35s
