### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by MAX2136** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#91]
My game crashes when trying to load up a world. It gets to the menu fine, but as soon as I load a world that used Drillgon's 1.12.2 port, it crashes with the description "Ticking block entity." I have included a crash log. Please excuse any mistakes, English is not my first language. PS. Making a new world is fine, I just cannot load the one with the old port. 
[crash-2023-04-12_11.40.11-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11209908/crash-2023-04-12_11.40.11-server.txt)

**Comment by Alcatergit** [comment]
Ah thats an easy one. All you need to do is break the battery blocks and then you can upgrade.

**Comment by MAX2136** [comment]
Thank you so much, it worked!
