### ISSUE TITLE
Version 1.9.4.a big doors dont stay open with buttons

### ISSUE THREAD

**Issue by Njet75** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#93]
Maybe this is intended but big doors don´t stay open when opening with buttons.They open and close automatically.
Only way to make stay open is with lever.

**Comment by artificialai223** [comment]
Yep, I get this issue too. Even if it is a feature, it is not a good one and should be removed.

**Comment by Alcatergit** [comment]
They work like Iron Doors now. That makes redstone control much easier and the doors dont flip direction. If it is powered by redstone you always know that it is open. If you want a button to toggle it you can create a small x-or gate via the redstone-over-radio blocks.
