### ISSUE TITLE
Multiblocks missing from Multiblock Structure Marker

### ISSUE THREAD

**Issue by Juff-Ma** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#95]
As far as i can see many structures are missing from the Multiblock Structure Marker, for example the fusion reactor.

Is this intentional? And if not can you add them?

**Comment by Alcatergit** [comment]
Yes that is intentional. The old fusion reactor model is not used anymore and the new shows up directly when placing the fusion core block somewhere.
