### ISSUE TITLE
Bug: Gas Te Recursion Overflow

### ISSUE THREAD

**Issue by Sora-Comic** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#97]
crash upon loading a gas pocket? when relogging into world gas is gone and crash does repeat until another pocket is generated

i am running with quite a few mods might be an incompatibility, im running 1 version prior to the newest version though the same crash happens on the newest version aswell

[crash-2023-05-01_18.25.51-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11368828/crash-2023-05-01_18.25.51-server.txt)

**Comment by Alcatergit** [comment]
That bug should be fixed in the next update

**Comment by Sora-Comic** [comment]
when will that be? i'm trying to start a server with some friends and this bug is killing the game when i try and go pretty much anywhere

> That bug should be fixed in the next update
