### ISSUE TITLE
crash when connecting to server

### ISSUE THREAD

**Issue by Castanea43** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#98]
Hi, i made a modpack but when i want to connect on my server, server crash

the crash log :
[crash-2023-05-01_08.05.50-server.txt](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/files/11372690/crash-2023-05-01_08.05.50-server.txt)

what the problem in multiplayer, in single its ok ?
Thanks in advance.

**Comment by Alcatergit** [comment]
Some other mod has overwritten or removed a part of minecraft that makes particles work.

java.lang.NoClassDefFoundError: net.minecraft.client.particle.Particle
